### ISSUE TITLE
la liste des rapports précédents

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#102]
Which course: this form What type of content: la liste des rapports précédents URL: https://docs.google.com/forms/d/e/1FAIpQLSepiYJTpT-6qEJ1RyLbHOYOT39MzVw1fKl-5MDIp55VVfA4Kw/viewform Description: j'aimerais avoir un lien direct sur cette liste sans devoir envoyer un formulaire à nouveau  or elle n'est accessible qu'après un envoi  je dois donc en réenvoyer un quand je rouvre mon navigateur de plus on n'a pas de correspondance entre les commentaires et les parties de cours concernées on a la liste des url  chez moi ça ne fonctionne pas en cliquant mais le copier-coller est ok  le problème est que JE n'arrive pas à deviner de quoi il est question  s'il faut cliquer sur chacune l'intérêt de les avoir diminue formtement :-/ other comments: cette liste est déjà bien mais ne pas pouvoir sauf par devinette relier un commentaire à un point précis du cours est vraiment dommage your name: klotsy screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: win xp which web browser? iron 49 Status actuel:

**Comment by petraBT** [comment]
The move to github should solve this problem.
