### ISSUE TITLE
questionnaire

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#13]
Which course: 1 Getting Started What type of content: questionnaire URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/e7e7818c173942e3b4e989cdc05e08d3/6?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40vertical%2Bblock%40788114fbf33b466da0d01579f514ab68 Description: je ne suis pas vraiment d'accord avec les réponses attendues à  To start working through the course materials I need to check the following:   pour la bonne raison que mon navigateur n'est PAS à jour même s'il est récent et que c'est srware iron (bon c'est presque chrome mais pas chrome...) et que tout fonctionne tout de même other comments: je suggère navigateur suffisamment récent et firefox ou chrome et dérivés  your name: klosty screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel: Comme le quiz n'est pas noté  est-ce que l'on peut considérer que c'est OK ?

**Comment by EllaHa** [comment]
Ravie de voir que tout fonctionne sur une solution comme Srware Iron. Nous proposons ce quiz pour la grande majorité d'apprenants. C'est donc plus à titre informatif en prévention d'éventuels problèmes techniques que nous mettons ce quiz. Si ça vous va, nous allons le laisser tel quel.

**Comment by klotsy** [comment]
c'est comme vous voulez mais je trouve ça dommage...
