### ISSUE TITLE
Codecast  subtitles  many typos

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#162]
Which course: 3 Modular Programming and Memory Management What type of content: Codecast  subtitles  many typos URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/37c45e787250473ebf3b8b1a30ce0a93/b5bac8c40dcc44928bdcddfb319b2abc/1 Description: - 0'43 : it isn't b but d in  Let's put 42 as a value  then a double  double b  the value  - 1'50 : I need instead of  I need's  in  First  I will get the address of the variable a  for what I need's  - 2'56 : it's  at this address  not  add this address  -3'55 : Many typos here ... It should be :  D. Let's do the same prinft. Address of d  percent p  backslash n  then address of d.  instead of   B. Let's do the same printf.Address of e  percent b  right slash  then address of p.  -4'15 : char star instead of  R star address of c.  -4'34 :  back slash n  instead of  Right slash.  -5'03 : Codecast instead of  codcast  in   with this special line here that is specific to the codcast  -7'30 : same one (codcast)  So that means that codcast is working in 32 bits mode.  - 8'16 : it's percent p not  person p  in  You also know how to print a pointer with person p.   other comments:  your name: Kitkatniss screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Windows 10 which web browser? Firefox Status actuel:

**Comment by Kitkatniss** [comment]
For mooc3 subtitles review

**Comment by Kitkatniss** [comment]
I've checked all this : all corrections were made.

**Plus : subtitles of Mooc3 are very close to be ready !** 

Close this issue

**Comment by Kitkatniss** [comment]
#157 
#158 
#160 
#159

**Comment by Kitkatniss** [comment]
All correction are in framapad document too ;)
https://bimestriel.framapad.org/p/u3-3_cc_pointers
