### ISSUE TITLE
exercice correction

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#166]
Which course: 3 Modular Programming and Memory Management What type of content: exercice correction URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/5c40ed165b45423496c1c8c8fdca08d9/91f8edcd857f410b82baa1860866f4ae/ Description: The correction of the exercice gives the  hello world  program ! other comments: A lot of work was to do just in order to display MB  KB and B your name: Kitkatniss screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Windows 10 which web browser? Firefox Status actuel:

**Comment by Kitkatniss** [comment]
The correction is fixed.

(I coud do the exercice without any sizeof)

**Comment by remisharrock** [comment]
thanks
