### ISSUE TITLE
exercice 8

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#167]
Which course: 3 Modular Programming and Memory Management What type of content: exercice 8 URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/37c45e787250473ebf3b8b1a30ce0a93/5e3d6a0c79904e539a702fc6d18c4b4f/?child=first Description: submit answer points to  There are no tests for this task.  other comments:  your name: Kitkatniss screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Windows 10 which web browser? Firefox Status actuel:

**Comment by Kitkatniss** [comment]
the exercice was changed

close this

**Comment by remisharrock** [comment]
thanks
