### ISSUE TITLE
typo in the title

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#168]
Which course: 3 Modular Programming and Memory Management  title What type of content: typo in the title  URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/37c45e787250473ebf3b8b1a30ce0a93/5e3d6a0c79904e539a702fc6d18c4b4f/?child=first Description:  Modify an integer variable value using a functions with pointers  : if it's a function  there's no  s   other comments:  your name: Kitkatniss screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Windows 10 which web browser? Firefox Status actuel:

**Comment by Kitkatniss** [comment]
typo in the title of the second codecast

**Comment by remisharrock** [comment]
I fixed it
