### ISSUE TITLE
Subtitles not showing up (impossible to select English subtitles) 

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#194]
Which course: 2 Language Foundations What type of content: Codecast URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/f2a41407085b4e8c8a5604123388ef33/a063aadae7944837bb71ed4f726e0370/?child=first Description: No subtitles (I'll try to write them) other comments:  your name: Isa screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel:

**Comment by Kitkatniss** [comment]
All texts from Mooc 1 and Mooc2 have been reviewed.

Have they been put back in rights places  ?

**Comment by Kitkatniss** [comment]
#30

**Comment by Kitkatniss** [comment]
#31

**Comment by mgoudz** [comment]
Subtitles are still missing as of this update. Here's the direct Codecast link: https://codecast.france-ioi.org/v6/player?stepperControls=_undo,_redo,_expr,_out,_over&base=https%3A%2F%2Ffioi-recordings.s3.amazonaws.com%2Fdartmouth%2F1518204459525

**Comment by mgoudz** [comment]
#30 and #31 are both closed.

**Comment by EllaHa** [comment]
The subtitles is there, but not showing up. I report the bug to the developpers.

**Comment by EllaHa** [comment]
Please empty your cache. This has been fixed.
