### ISSUE TITLE
Progression

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#197]
Which course: 5 Advanced Data Types What type of content: Progression URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/courseware/58099ea386614233830b63363dc6db01/d25d4867ce6a4cd1929358ee146903cc/?child=first Description: Les activités 10 à 14 ne sont pas prises en compte dans la progression. Pour l'activité 14 à laquelle il manque l'énoncé j'ai soumis le code fourni. L'activité référencée par l'url plus haut est bien prise en compte malgré le message d'erreur  There are no tests for this task.  (il y a bien 1 test) other comments:  your name: julien B screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Windows 10 which web browser? Google Chrome Version 69.0.3497.100 (Build officiel) (64 bits) Status actuel:

**Comment by EllaHa** [comment]
fixed
