### ISSUE TITLE
Filling forms

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#198]
Which course: 1 Getting Started What type of content: Filling forms URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/7f15846e372741c483ee67f37d93f346/?child=first Description: Filling form change place to the left when filled covering check marks/boutons. other comments:  your name:  screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Windows 10 which web browser? firefox 62.0 (64 bits) Status actuel:

**Comment by mgoudz** [comment]
This is related to #7 and has been fixed.
