### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#222]
Which course: 3 Modular Programming and Memory Management What type of content: broken link URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/9afb1233a3d74a62acc1625236e57a96/e1f1485b07334f1297e71f4f4896e77d/?child=first Description: The  please click here  link to go to the codecast site if the iframe doesn't load doesn't work. I screen-shotted the error message. other comments:  your name: David screenshot: Broken_Codecast_Link Codecast timing:  Tasgrader code submitted:  Operating system: Apple's macOS (formerly OS X) which web browser? Chrome version 68.0.3440.106 Status actuel: Done Ella

**Comment by mgoudz** [comment]
Fixed
