### ISSUE TITLE
exercice Programming a toaster

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#229]
Which course: 3 Modular Programming and Memory Management  Programming a toaster What type of content: exercice Programming a toaster URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/5c40ed165b45423496c1c8c8fdca08d9/91f8edcd857f410b82baa1860866f4ae/ Description: so much work just to print the answer ! and the correction gives the  hello word  program ! other comments:  your name: Kitkatniss screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Windows 10 which web browser? Firefox Status actuel:

**Comment by chrissmiller** [comment]
previously resolved
