### ISSUE TITLE
Codecast  Testing subtitles

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#24]
Which course: 1 Getting Started What type of content: Codecast  Testing subtitles URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/6e554ffe0eb345c4a343a63b4f436db5/67d05789483a44bf8c3b095b974c188a/?child=first Description: suggestion : is it possible to display the subtitles (strip) above the Input/Output/Terminal   just under the code ? other comments:  your name: Kitkatniss screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel:

**Comment by EllaHa** [comment]
You can move the subtitle strip by clicking on it if you want.
