### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#243]
Which course: 4 Pointers and Memory Management What type of content: Link URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2018/courseware/b0efc6858fa44aeeb0b482018e0abf01/622f95d2f08e4f0db6fb9770a31464d0/?child=first Description: The  please click here  link to load the codecast externally didn't load. The  preparing playback  bar never loads. other comments:  your name: David screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Apple's macOS (formerly OS X) which web browser? Chrome 68.0.3440.106 Status actuel:

**Comment by EllaHa** [comment]
fixed
