### ISSUE TITLE
Codecast  wrong subtitles file

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#244]
Which course: 2 Language Foundations  subtitle What type of content: Codecast  wrong subtitles file URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/f2a41407085b4e8c8a5604123388ef33/6864db5ab681423d855d42c487c09052/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40vertical%2Bblock%40c526c85830564d2baafefd5f90d8b6a5 Description: The subtitles here don't go with the codecast Isa  others and I rewrited or reviewed them (see framapad document) other comments:  your name: Kitkatniss screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Windows 10 which web browser? Firefox Status actuel:

**Comment by EllaHa** [comment]
Solved
