### ISSUE TITLE
exercice / course

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#246]
Which course: 1 Getting Started  exercice / course What type of content: exercice / course URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/0b97cbce20fe40148cf7ff017a106a9e/?child=first Description: In the course  it's written :  return 0  In the exercice correction  it's written :  return(0)  Is it intended ? Is it the same ? other comments:  your name: Kitkatniss screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Windows 10 which web browser? Firefox Status actuel:

**Comment by deladan** [comment]
Hi Kitkatniss!
It's the same but technically, return isn't a function so doesn't need parentheses.

**Comment by Kitkatniss** [comment]
ok, thx

Close this report
