### ISSUE TITLE
subject of the exercice : \n is missing

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#25]
Which course: 1 Getting Started What type of content: subject of the exercice : \n is missing URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/6e554ffe0eb345c4a343a63b4f436db5/67d05789483a44bf8c3b095b974c188a/?child=first Description:     printf ( Still not convinced? \n )  this \n is expected by Taskgrader in the answer other comments:  your name: Kitkatniss screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel:

**Comment by chrissmiller** [comment]
fixed
