### ISSUE TITLE
Wrong overview for Linux

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#256]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/085327718ea14d3b8168dc7943f40aba/f918edda3be84715aca7f33d1a383205/?child=first 

This is not the text for the course overview of Linux : wrong text :

Course overview
In this course, you will learn the principles of C programming and start coding hands-on in a browser tool that will provide instant feedback on your code.

You will get started with C and learn how to write your first programs, how to make simple computations and print the results to the screen, how to store values in variables and how to repeat instructions using loops. 

Beginners, even those without any programming experience, will be able to immediately start coding in C with the help of powerful yet simple coding tools right within the web browser. No need to install anything!

**Comment by EllaHa** [comment]
Solved
