### ISSUE TITLE
first question without the video to explain before

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#258]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/632a112f8d4e46c88cf195f34e486a4f/55e5847158bc402b981467401d8ead19/?child=first

the 1st question of the quizz doen't have any explanation before. We should add the memory video from the other MOOC

**Comment by remisharrock** [comment]
mettre la vidéo 

Memory representation, RAM, cells, word, byte, bit, memory address 

en première unité de la sous-section

**Comment by EllaHa** [comment]
Fixed
