### ISSUE TITLE
Quiz and imprecise question

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#262]
In course 1, activity about special characters : https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/09151bec3f5c43f2b56e181e2ad87d03/2?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40vertical%2Bblock%4071c0d2e569d847ef8afbb95f4937c7d5
third question : maybe the type of the expected brackets should be mentioned (square brackets - not to confuse them with angular brackets).
(issue raised on the forum by a learner)

**Comment by remisharrock** [comment]
Fixed! Thanks for this !!
