### ISSUE TITLE
video welcome course 1 - bad subtitles

### ISSUE THREAD

**Issue by klotsy** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#264]
Hi,   
Isa has done good subtitles fort this video, and the actual subtitles are bad (Rami Sharak ?) and later it's not better...
 https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/414002e0d1444d5aade9921f6fe4aee6/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40vertical%2Bblock%40e4f484ae81c9401f84ac0e6fcaf8e64a 
![ramisharak](https://user-images.githubusercontent.com/42912762/46365620-5f7a6780-c679-11e8-86e7-9ace46d44dc9.jpg)

**Comment by EllaHa** [comment]
Hi @klotsy,
Thanks for raising this issue. David in our team updated all codecast subtitle corrections that you suggested on Framapad. Thanks for this fantastic job. This in in progress for videos!

**Comment by klotsy** [comment]
Bonjour @EllaHa ,   
il y a aussi des choses à revoir dans les nouveaux sous-titres (ceux qui n'existaient pas encore) une vidéo du cours 6 par exemple que je viens de regarder - comment fait-on ? toujours avec les framacalc ?

**Comment by EllaHa** [comment]
Bonjour Klotsy, 
Merci pour tout le travail, c'est fantastique !
Le Framacalc semble bien fonctionner. Qu'en penses-tu ? 
La seule chose c'est que David ne peut mettre à jour les srt sur la plateforme qu'à un instant T (c'est un upload et non un fichier dynamique) ce qui implique d'arrêter une date sur la modification possible des fichiers. 
Ou s'il y a modification après upload par David sur la plateforme, il conviendrait d'ouvrir une nouvelle issue de type "j'ai mis à jour le fichier sur Framacalc".

**Comment by klotsy** [comment]
le framacalc et le framapad c'est bien mais il faudrait rajouter une colonne  "plateforme ok" ou quelque chose du genre  
faire des issues pourquoi pas si on remodifie après mise en ligne il faudrait voir avec les autres correcteurs : isa, Kitkatniss, R_E... j'avais vu des David_transcript t.done dans le framacalc du cours 3 mais juste quelques uns

**Comment by EllaHa** [comment]
Je fais le point avec David et on revient vers vous !

**Comment by klotsy** [comment]
il manque les sous-titres des codecast du cours 5... (j'ai crééé une issue pour ça)  peut-être serait-ce mieux de les relire avant publication ? ou pas ?

**Comment by Kitkatniss** [comment]
following this...

**Comment by Kitkatniss** [comment]
Same trouble with the subtitles of the last video of this course

Text should be https://bimestriel.framapad.org/p/u1_conclusion

**Comment by Kitkatniss** [comment]
@EllaHa I'll send a video of this, on github : 
Les images et le son sont dégradés, au début

**Comment by Kitkatniss** [comment]
We really need feedback from you about subtitles, please !

Is someone at your side writing the subtitles for the videos (mooc6 mooc7) ?
Do you have an ETA ?
Who do what ?

**Our time is too precious for wasting it !**

**Comment by klotsy** [comment]
il y a des sous-titres pour le cours 6, mais **pas pour le 7**

**Comment by deladan** [comment]
Je peux me charger d'écrire les sous-titres pour le cours 7 (mais j'aimerais être sûre que d'autres ne sont pas déjà en train de travailler dessus)
.

**Comment by Kitkatniss** [comment]
mooc6's subtitles have to be reviewed...

So I'm doing that, at the moment. .. still in progress...

But it takes much much much time. And I DO need to know if it's useful ??

**Comment by Kitkatniss** [comment]
@EllaHa @remisharrock @mgoudz

**Comment by petraBT** [comment]
This is leftover from pre-testing. Addressed by now. Closing.
