### ISSUE TITLE
activity 12, 13 & 14 don't seem to be "connected" to the right activity in 5.3

### ISSUE THREAD

**Issue by GodefroyClair** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#268]
I passed activities "Activity: is the number divisible by 3?" & "Activity: count redundancies in number"  (not "" because of an issue reported earlier) but my progression doesn't show that and it is stuck at 79% with last 3 activities (12, 13, 14) saying when you hover them:
"Activity XX - Unreleased - 0%"
This could be unrelated but I noted that:
1) no beta testers have reported this problem before - as far as I know
2) you have recently changed something on the previous activities of this unit 5.3 (up to 11) by adding a tab "Do you need help?" where you ask if we want you to "reveal solution for previous activity"?
So could this be related? Could it be related to my personal case (as I have started unit 5.3 a week ago and only resumed today.) ?

**Comment by EllaHa** [comment]
You are right GodefroyClair, there was a problem there. 
You should now be able to see your progression. 
Please let me know if that works!

**Comment by EllaHa** [comment]
@GodefroyClair can you please resubmit your code on the taskgraders?

**Comment by GodefroyClair** [comment]
Hi Ella,
I did and now it works. 👍
