### ISSUE TITLE
MOOC 3 (3.1) - Activity: Program a smart unit converter, there is an error in the statement.

### ISSUE THREAD

**Issue by cdnhermit** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#269]
In Activity: Program a smart unit converter, there is serious an error in the problem statement.
[https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/9afb1233a3d74a62acc1625236e57a96/07d4663586b74bd6abd7b94bf3326474/?child=first]

Here are the conversion rules to use:
1 foot = 0.3048 meters;
This is in error. It should be 3.28084 or more digit but the sandbox will not accept more digit than that. Even with this correction, the submission does not go through because my answer will not match the expected answer.
Sandbox:
In the sandbox, as soon as I enter the if statement, [ if(unit == ‘m’) ], my variable double foot, is changed to 0 for no apparent reason. Not very convenient.

 
  
Taskgrader 
[Bug #1.docx](https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/files/2440392/Bug.1.docx)
Submission:
 

My CodeBlock:
 

Also, it took me quite a long time before I try %s for a character. This was not explained. The letter m or c or f are not string but individual characters and therefore I can not comprehend why I needed to use the %s for my program to work. Any explanation is more than welcome.

As I can't attach picture, here is a file explaining every thing.

**Comment by cdnhermit** [comment]
I am under Windows 10 Pro (64 bit)  1803 (17134.285) et Firefox 62.0.2 64bit

**Comment by chrissmiller** [comment]
Hi cdnhermit,

The conversion rule is correct - since that rule indicates that 1 foot = .3048 meters, you must divide the number of meters by .3048 to find the number of feet. Could you upload the code in which you tried %c instead of %s but the code was marked incorrect? I am using %c without a problem so I have not been able to reproduce that issue

**Comment by deladan** [comment]
Hi @cdnhermit,
I think your issue is that the %c format specifier will read any character. And space is a character.  
So you'll have to make scanf read the space between the two numbers as well.  
Something like scanf("%lf %c", &value, &unit) should do the trick.

**Comment by cdnhermit** [comment]
Bonjour Isabelle,

J'avais fait cela et cela ne fonctionnait pas.

Merci
________________________________

**Comment by deladan** [comment]
Avec une espace entre %lf et %c ?
Le problème devait être ailleurs, alors.
N'hésite pas à poster le code en question, ce sera plus simple pour voir où il se trouve.

**Comment by cdnhermit** [comment]
Hello, for some reason %c is working today.

When my code produces errors, I am trying to correct it but when I don't understand the error  I am getting, as the one I currently have, I finish by undoing what's correct and it becomes incorrect.  For the meter formula, I apologize, it was my error as I did not apply the correct operation.
Now, my code produce an error. One that was previously mentioned. This time, I am not changing anything. As my suffix lbs is perfectly printed, I can't understand why the suffix ft is not displayed.

```
#include <stdio.h>
int main() {

    int nbrConversion = 0;
    double amount = 0;
    double foot = 0.3048;  //meters conversion
    char unit;
    char ft[3] = "ft";
    char lbs[4] = "lbs";
    double pound = 0.002205; // pounds conversion

    int i = 0;

    scanf("%d", &nbrConversion);

    for (i = 0; i < nbrConversion; i++){
        scanf("%lf %c", &amount, &unit);

        if (unit == 'm'){
            printf("%.6lf %s\n", (amount / foot), ft);
        }else if(unit == 'g'){
            printf("%.6lf %s\n", (amount * pound), lbs);
        }else if(unit == 'c'){
            unit = 'f';
            printf("%.6lf f\n", (32 + 1.8 * amount));
        }
    }
    return 0;
}

```
The error is that taskgrader does not print my suffix ft.

 Test #1     Wrong answer in 0 s
Your program displayed :

40.354331  
2.745761 lbs
98.960000 f

... 

While the expected answer was :

40.354331 ft
2.745761 lbs
98.960000 f


![activity 3 1 a smart unit converter](https://user-images.githubusercontent.com/43022830/46519695-458e7f80-c847-11e8-9eca-133856badab6.png)

**Comment by deladan** [comment]
I've just tried to submit your code, and it was accepted.  
Maybe you should try once again

**Comment by deladan** [comment]
I've just tried to submit your code, and it was accepted.  
Maybe you should try once again

**Comment by chrissmiller** [comment]
I think this is resolved, going to close unless it pops up again!

**Comment by mhddaas** [comment]
#include <stdio.h>
int main() {

    int nbrConversion = 0;
    double amount = 0;
    double foot = 3.2808;  //meters conversion
    char unit;
    char ft[3] = "ft";
    char lbs[4] = "lbs";
    double pound = 0.002205; // pounds conversion

    int i = 0;

    scanf("%d", &nbrConversion);

    for (i = 0; i < nbrConversion; i++){
        scanf("%lf %c", &amount, &unit);

        if (unit == 'm'){
            printf("%.6lf %s\n", (amount * foot), ft);
        }else if(unit == 'g'){
            printf("%.6lf %s\n", (amount * pound), lbs);
        }else if(unit == 'c'){
            unit = 'f';
            printf("%.6lf f\n", (32 + 1.8 * amount));
        }
    }
    return 0;
}


now it is working

**Comment by hibrohi** [comment]
> #include <stdio.h>
> int main() {
> 
> ```
> int nbrConversion = 0;
> double amount = 0;
> double foot = 3.2808;  //meters conversion
> char unit;
> char ft[3] = "ft";
> char lbs[4] = "lbs";
> double pound = 0.002205; // pounds conversion
> 
> int i = 0;
> 
> scanf("%d", &nbrConversion);
> 
> for (i = 0; i < nbrConversion; i++){
>     scanf("%lf %c", &amount, &unit);
> 
>     if (unit == 'm'){
>         printf("%.6lf %s\n", (amount * foot), ft);
>     }else if(unit == 'g'){
>         printf("%.6lf %s\n", (amount * pound), lbs);
>     }else if(unit == 'c'){
>         unit = 'f';
>         printf("%.6lf f\n", (32 + 1.8 * amount));
>     }
> }
> return 0;
> ```
> 
> }
> 
> now it is working

but they have told to use the function call to this program

**Comment by deladan** [comment]
Hello @hibrohi ,
From problem statement:  

> You may use functions to complete this exercise, but **that is not required**.
