### ISSUE TITLE
one answer can't be accepted because of its format

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#270]
In the quiz about Linux and files, the answer of the 7th question causes an error when submitting ; it is considered as a mathematical formula...  
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/953455675ecb40e491f6645e3711295f/0f6bc45e0328471ba775d27853a83b82/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40discussion%2Bblock%4077b4b5e2b6c24fcf91eeb945d5043735
(issue raised by a learner on the forum)

**Comment by klotsy** [comment]
this is a new problem,  last week it was ok. submission is impossible.
![9p](https://user-images.githubusercontent.com/42912762/46396711-79a35c80-c6f0-11e8-985e-2bff966d0d4e.jpg)

**Comment by EllaHa** [comment]
Hi Isabelle, 
thanks for reaching out. 
Should now be fixed. 
I have cleared you number of attempts for this question so should be able to resubmit. 
Best, 
Ella

**Comment by deladan** [comment]
Hi Ella,  

I don't really bother about my grades, so it wasn't necessary to clear the number of attempts. Especially as this issue prevent us to submit answers, so I've got all of my attempts yet ;-)
