### ISSUE TITLE
6.2 quiz linux and the files, question 10 answer false ?

### ISSUE THREAD

**Issue by klotsy** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#271]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/jump_to/block-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018+type@vertical+block@763219d8a6a64fbfa6ad6227231df4c0
the response   
`mv ../miscellaneous ../others`
appears wrong...
![misc](https://user-images.githubusercontent.com/42912762/46398916-ace8ea00-c6f6-11e8-8a5a-c80ac0a60b03.jpg)

**Comment by EllaHa** [comment]
Hi Klotsy,
Seems to be without a "s" at the end of "other"
 "mv ../miscellaneous ../other" 
Best,

**Comment by klotsy** [comment]
yes it works... change the statement ?

**Comment by EllaHa** [comment]
Just did it.  @remisharrock can you confirm this is OK?

**Comment by EllaHa** [comment]
Merci Klotsy !
