### ISSUE TITLE
Link to wiki

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#273]
A learner post: In the "Learn how to post code on the edX forum" module there is a link to the "How to post code on the edX forum" wiki which is directed to the EDIT page not the VIEW page so the hyperlinks to the view etc do not work. This may be confusing for some. 
It's indeed confusing. The link is on this page: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/e4ee673e89a9468ebd5a0d66d608db29/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40vertical%2Bblock%40a4c7203ecb4a405a83dc8068f00a6b4c

**Comment by EllaHa** [comment]
Thanks this is solved!
