### ISSUE TITLE
use notes

### ISSUE THREAD

**Issue by klotsy** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#275]
I don't can use Notes ... I never had a pencil icon, and I can't add a note with the Notes tab. 
Should I allow a special url, cookies... for this ?
J'aimerais voir ce que ça donne, si quelqu'un pouvait poster une copie d'écran ? @deladan ?
![notes](https://user-images.githubusercontent.com/42912762/46413473-4927e680-c721-11e8-88ec-2eb9e5555a93.jpg)

**Comment by deladan** [comment]
Bonjour Klotsy,

Les notes s'écrivent au fur et à mesure de la lecture.  
Il faut sélectionner la partie du texte que tu veux commenter. Lorsque tu lâches la souris, l'icône avec le crayon apparaît. 
Si tu cliques sur cette icône, tu peux alors saisir du texte, puis enregistrer.
Tu accèdes ensuite à tes notes par l'onglet correspondant, ou bien en retournant sur la page que tu as commentée.

Icône lorsque tu sélectionnes du texte:
![capture d ecran de 2018-10-03 15-36-35](https://user-images.githubusercontent.com/34571147/46414184-dae42380-c722-11e8-93b6-dce8ea18c25f.png)
Zone de saisie des notes:
![capture d ecran de 2018-10-03 15-36-50](https://user-images.githubusercontent.com/34571147/46414192-e0da0480-c722-11e8-9ec9-7d630c1b45c8.png)

**Comment by EllaHa** [comment]
Exactement, merci Isabelle pour cette réponse !

**Comment by klotsy** [comment]
merci, ça marche :-) mais c'est expliqué où ?

**Comment by deladan** [comment]
Je ne sais pas, trouvé ça au hasard de mes divagations sur edX ;-)

**Comment by klotsy** [comment]
par hasard c'est bien le problème ;-)
![notes2](https://user-images.githubusercontent.com/42912762/46414536-a02ebb00-c723-11e8-9889-7d8c41a2590c.jpg)

**Comment by deladan** [comment]
À signaler directement à edX je pense

**Comment by klotsy** [comment]
ou mettre une petite explication quelque part, comme pour codecast, peut-être en épinglé sur les forums ou en intro...
