### ISSUE TITLE
6.2 quiz cat less more question 2 not clear

### ISSUE THREAD

**Issue by klotsy** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#279]
dans cette question on parle de `<enter>` et`<CTRL+D>` mais type ici ne fait pas partie de la commande, ça veut juste dire qu'on doit taper peut-être faudrait-il le mettre entre <> ou ne pas le mettre du tout... et il faut `<enter>` après cat > f sinon ça ne fonctionne pas  
le retour à la ligne de la question n'est pas parlant dans la mesure où on écrit `<enter>` ensuite
pour moi la bonne réponse serait  (avec ou sans saut de ligne)
`cat > f ` `<enter>` `hello` `<enter>` `<CTRL+D>`
![cat](https://user-images.githubusercontent.com/42912762/46423504-fce7a100-c736-11e8-8255-09ae4401e775.jpg)

**Comment by remisharrock** [comment]
absolument, je corrige

**Comment by remisharrock** [comment]
c'est bon ?

**Comment by klotsy** [comment]
très bien
