### ISSUE TITLE
sandbox

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#28]
Which course: 1 Getting Started What type of content: sandbox URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/55a5f7cce4c545298ad86a6a3ec4fc8d/ Description: if I send my code in the sandbox and run the program  the screen is not showing correctly. (I can send screenshot)  I tested in Fun version  it still works. other comments:  your name: Kitkatniss screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel:

**Comment by EllaHa** [comment]
We need more input from Kitkatniss to understand the issue.

**Comment by Kitkatniss** [comment]
I've checked again 👍 

I was surprised with the "output /input" could also be  an interactive terminal

close this issue, it's ok
