### ISSUE TITLE
6.3 quiz compilation question 3 no good answer

### ISSUE THREAD

**Issue by klotsy** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#282]
je rêve,  ou aucune des réponses proposées n'est bonne ?
![compile](https://user-images.githubusercontent.com/42912762/46425566-4ab2d800-c73c-11e8-9202-ddd018c755a4.jpg)

**Comment by remisharrock** [comment]
aïe des espaces en trop !

**Comment by remisharrock** [comment]
c'est corrigé :)

**Comment by klotsy** [comment]
euh non, en fait c'est qu'il n'y a aucune réponse qui exécute le binaire qui vient d'être créé...

**Comment by remisharrock** [comment]
sisi, j'en vois une

**Comment by klotsy** [comment]
moi pas alors laquelle ?

**Comment by remisharrock** [comment]
sur la vidéo Compile a C program using GCC juste avant à 1min40 , on est d'accord ?

**Comment by klotsy** [comment]
oui, je ne l'avais pas regardée j'avoue , a.out est la sortie par défaut ce que j'ignorais

**Comment by remisharrock** [comment]
tu veux reseter tes essais quizz ?

**Comment by klotsy** [comment]
j'avais pas <s>validé</s> soumis celui-ci avant lol, c'est bon ;-)
