### ISSUE TITLE
6.3 quiz compilation question 2 space errors in statement

### ISSUE THREAD

**Issue by klotsy** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#284]
il y a des erreurs d'espace : 
`number> = 1` 
`% d \ n`
d'où des erreurs de compilation au copier-coller, bien entendu
![erreursprog](https://user-images.githubusercontent.com/42912762/46425957-65d21780-c73d-11e8-8532-ed6dc7879bda.jpg)

**Comment by remisharrock** [comment]
corrigé, mieux comme ça ?

**Comment by klotsy** [comment]
celui-ci passe :-)
