### ISSUE TITLE
course 7 (entire) no video has subtitles

### ISSUE THREAD

**Issue by klotsy** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#288]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+2T2018/courseware/f838e66a12864002be52ceaf73f2842f/40bb9e617e054eada1ceb844aced1a5d/?child=first 
and 
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+2T2018/courseware/f838e66a12864002be52ceaf73f2842f/20c36bf48d224858a37200c5de92cf3f/?child=first

**Comment by mgoudz** [comment]
The video IDs need to be swapped out in Studio. 7.1 and 7.2 are fixed.

**Comment by mgoudz** [comment]
Subtitles are now displaying correctly in all videos in course 7.
