### ISSUE TITLE
7.1 taskgrader use the math library 

### ISSUE THREAD

**Issue by klotsy** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#289]
d'abord petite faute de frappe dans l'énoncé : 
*Your program's source code **si** stored*  
ensuite taskgrader ne veut pas de l'ordre des commandes de compilation pourtant utilisé dans le cours et sort l'erreur 
*It looks like your compiler command is in the wrong order - list the source code before the executable file name, separated by the -o flag. (-5 points)*  
alors que 
`printf("gcc -std=c11 -Wall -fmax-errors=10 -Wextra /usr/lib/libm.a program.c -o program\n");`passe  
agaçant... 

cours
![llecours](https://user-images.githubusercontent.com/42912762/46442089-d4789a80-c768-11e8-8736-6cbe7636b45b.jpg)  
taskgrader
![taskgrad](https://user-images.githubusercontent.com/42912762/46442098-d93d4e80-c768-11e8-9252-81e6dea78e0c.jpg)

**Comment by petraBT** [comment]
Chris, can you look into this? Currently, points are being deducted if the library isn't listed before program.c, but as long as it is listed before the -o flag this should be graded as correct.

**Comment by chrissmiller** [comment]
Whoops - fixed!
