### ISSUE TITLE
bad example output

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#292]
In the course2, activity repeat a word: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/f2a41407085b4e8c8a5604123388ef33/a063aadae7944837bb71ed4f726e0370/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%40a9ecef65da07480a816ff4a5c0655808
The first example should print out words in lowercase, as is the word read from the input.
(issue reported by a learner on the forum)

**Comment by petraBT** [comment]
Fixed!
