### ISSUE TITLE
Issue with a solution

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#293]
Course 1, activity divide decimal : https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccb75017dce84804a4477600cf09014d/4c4f062124eb47f99ab23cf7228a1109/2?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%40715e665a06734408ae26af019de29230
The given solution don't exactly do what is expected. It will indeed give 16 as output for the first example given on the problem statement (only the result of the division should be rounded, no ?)
(issue raised by a learner on the forum)

**Comment by klotsy** [comment]
Hello, je ne suis pas d'accord, l'énoncé est clair : **"the largest number of books that you can purchase with the given amount of money."**
 on ne peut pas acheter un morceau de livre, et le vendeur ne va pas arrondir son prix à l'inférieur, j'ai commenté dans ce sens

**Comment by petraBT** [comment]
Fixed, thank you!
