### ISSUE TITLE
units 2.0 and 3.0 seem different in the structure, is it normal ? 

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#295]
Everything is in the title :)

**Comment by mgoudz** [comment]
@EllaHa it looks like 2.0 uses different sub-section/unit labels than the other courses. Could we change 2.0 match the others or is there a reason this is different? 
<img width="1234" alt="screen shot 2018-10-08 at 1 32 39 pm" src="https://user-images.githubusercontent.com/6576087/46624574-2c175d00-caff-11e8-9ad2-1fe1ff88ec38.png">

**Comment by mgoudz** [comment]
Ok, I fixed 2.0 to match the structure of the other courses
