### ISSUE TITLE
A bad configuration of Taskgrader

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#298]
In course 1, in the activity about robots (https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccf660cc6a1141e0a9bebfc515ce320a/76cd4b61bfd641de982b5f4f9a169ee6/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%4002bc7c036e874cd4b15818185a8d1c2e), a learner got this message: "Error you used 2 print statements. You should only use 1. (-50 points)" from the grader.
Indeed, if you use 2 printf, this message is showing.  
I don't know why he used 2 printf here but anyway, this message is quite confusing, and I wonder whether it isn't a remaining for a previous activity (print multiple lines with 1 printf)?

**Comment by klotsy** [comment]
là non plus je ne vois pas trop où est le problème ?

**Comment by deladan** [comment]
Taskgrader donne un message d'erreur qui n'a a priori aucun rapport avec l'activité.
Ici, le but n'est pas de faire utiliser une seule instruction printf.
Je me demande si ce n'est pas quelque chose qui reste d'un paramétrage de Taskgrader pour une des activités précédentes.

**Comment by klotsy** [comment]
je trouve que taskgrader donne un message correct, s'il y a deux printf c'est que le code ne donne pas la sortie unique demandée (un seul nombre) et donc que l'énoncé n'est pas respecté - l'exemple le montre bien...

**Comment by deladan** [comment]
Pas convaincue. Dans ce cas, on aurait droit au feedback habituel : votre programme a affiché ... alors qu'il était attendu ...
Et ce qui a interpelé l'apprenant, c'est surtout cette mention de -50 points.

**Comment by klotsy** [comment]
en même temps on n'a pas son code, et il peut recommencer...

**Comment by klotsy** [comment]
je viens de tester et l'erreur "votre programme a affiché " vient bien si le résultat est faux ou si on met un printf au début, ou si on met du texte dans le deuxième printf
ceci : 
> 	printf("%d", total);
> 	printf("\n");

reproduit exactement l'erreur sans autre message si on met autre chose que \n ou un ou des espaces dans le deuxième printf

**Comment by deladan** [comment]
Oui, je suis tout à fait d'accord.
Ce que je voulais dire, c'est que le message supplémentaire "vous avez utilisé deux printf" n'a pas sa place ici, car ce n'est pas vraiment une des contraintes de l'exercice.
Je pense que c'est plus perturbant qu'autre chose, et pas sûre que ce soit volontaire ici.

**Comment by petraBT** [comment]
Chris, when you get a chance could you check on the checker for the robot assignment (loopReadProcessIntegers)? There seems to be a remanent of a previous checker here that takes off points if the solution contains more than one printf statement (indeed, as is pointed out above, even for something like     
    printf("%d", sum);
    printf("\n");
one gets dinged.)

**Comment by chrissmiller** [comment]
Whoops, sorry about that - fixed!
