### ISSUE TITLE
Taskgrader: The solution given is not related to the exercise.

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#3]
3 Modular Programming and Memory Management 

Taskgrader 

https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/5c40ed165b45423496c1c8c8fdca08d9/91f8edcd857f410b82baa1860866f4ae/?child=first 

 The solution given is not related to the exercise.

Apple's macOS (formerly OS X) 

firefox

**Comment by petraBT** [comment]
Indeed, something is really wonky with C103 Week2 (the toaster) “MemorySpaceHumanized”:

The solution that shows up when one correctly solves the problem in edX is “hello world”, even though in task editor the correct solution can be found. What’s more, when I use “test task” from task editor, I get the correct solution but on the other hand the error message that there are no tests for my task.

![screen shot 2018-10-01 at 12 26 57 pm](https://user-images.githubusercontent.com/33522257/46301976-db8b8700-c575-11e8-97d0-26a17eb6c808.png)
![screen shot 2018-10-01 at 12 27 08 pm](https://user-images.githubusercontent.com/33522257/46301977-db8b8700-c575-11e8-81ef-d0ab301b7367.png)
![screen shot 2018-10-01 at 12 28 08 pm](https://user-images.githubusercontent.com/33522257/46301978-db8b8700-c575-11e8-9e19-e94b6b49b503.png)

**Comment by EllaHa** [comment]
Hi @petraBT 
It seems that I found an explanation. We created this task for the prototype week and then created a new one. 
I will see with Chris which task is actually the correct one.

**Comment by petraBT** [comment]
Hi @EllaHa 
I checked both tasks and the other one (with the lower case "m") is definitely not the correct one. Everything looks to be set up perfectly in "MemorySpaceHumanized". It's really strange. Yes, please have a look with Chris!

**Comment by EllaHa** [comment]
There was a problem with a taskgrader link. This is solved.

**Comment by EllaHa** [comment]
@petraBT please confirm us this is working on your side.

**Comment by petraBT** [comment]
@EllaHa Yes!!! All good.

**Comment by EllaHa** [comment]
Perfect!
