### ISSUE TITLE
Mooc 6 videos subtitles : why "speakers" ?

### ISSUE THREAD

**Issue by Kitkatniss** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#304]
Is it possible to change "speaker 1" and "speaker 2" for "Petra" or "Remi" in the subtitles of the videos ?

**Comment by klotsy** [comment]
and professor1, professor 2 too ?

**Comment by Kitkatniss** [comment]
yes, same !

**Comment by mgoudz** [comment]
Yes, that is possible, but would take quite a bit of work. We will address this after the other bugs are resolved. Thank you for the suggestion. @ddomonoske and @EllaHa can we make this change on the subtitles we are editing anyway for other reasons and then go back later to correct the others as time allows? Let's identify them as "Petra" and "Rémi"

**Comment by ddomonoske** [comment]
Yes, I'll start making that change. I believe Petra and Rémi only speak together in videos, correct? This would mean none of the Codecasts would have to change.

**Comment by Kitkatniss** [comment]
no, there are codecasts with both speaking together

I did the changes in Mooc3

Are-you using the framapad documents ? @ddomonoske

**Comment by Kitkatniss** [comment]
I suggest to remove "music playing" too

**Comment by Kitkatniss** [comment]
For Mooc 3, I wrote PETRA, REMI and removed "music playing"

**Comment by Kitkatniss** [comment]
done for all documents

**Comment by petraBT** [comment]
Looks like this has all been addressed. Closing this issue.
