### ISSUE TITLE
Issue #265 should be reopened...

### ISSUE THREAD

**Issue by GodefroyClair** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#305]
Please look at my answers to chrissmiller to see why.
Thanks!

**Comment by petraBT** [comment]
Chris, would it make sense (and is it possible) to only check whether the main function has been left intact rather than also checking in the prototypes? Students are less likely to change things there potentially?

**Comment by chrissmiller** [comment]
Hi @GodefroyClair  so sorry for the delayed response. Right now the checker is only checking the main function and the student structure. I have copied and pasted your code exactly as it is from #265 and it validates perfectly for me, and I cannot reproduce the issue with different spacing in printStudent causing any issues so I am somewhat baffled as to what could possibly be going on. Would you be able to go and re-paste the code that is causing the issue? I just can't seem to recreate the issue no matter what I'm changing in other functions...

**Comment by GodefroyClair** [comment]
Hi Chris,
You're right. I just used the exact same code that failed a few weeks ago and now I pass. So the problem seems to be gone.
