### ISSUE TITLE
quiz about variables (no issue)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#308]
A learner (aka Slays) finds out that we can declare a variable with its name between parentheses.
I've tried it and it actually works, but parentheses aren't actually part of the name.  

The question asks about authorized names, but the answers are declarations. That could be ambiguous.  

Here's the link to the message: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/997220ed923b292464b5742bf966083116fb1036/threads/5bb395483b0abc09960040b9
and the link to the quiz: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccf660cc6a1141e0a9bebfc515ce320a/486dacf4bd094519afe1c91af2e17fee/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%40cbacb57afab143ec93b53e6c5a1a8551

**Comment by klotsy** [comment]
dans le quiz, ce qui rend la variable  `int (counter pigs)` non valide, c'est l'espace, pas les parenthèses. mais effectivement peut-être que les int sont de trop ou qu'il faudrait reformuler la question : dans les déclarations de variables suivantes, quels noms...

**Comment by deladan** [comment]
Ah oui, au temps pour moi...
Voilà ce que c'est de vouloir aller trop vite. Je complète ma réponse dans le message.
