### ISSUE TITLE
unclear instructions on activity 5.3: free a linked list

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#309]
As a learner points out in the forum, the instructions say that we are provided with prototype for the freeStudents function.  
Actually, it turns out we have to write it as well as the function, so it may be a good idea to adjust the problem statement.

Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/courseware/ec78e06b33f444cb8265d8c58227da98/5a5737bdb1254f3b8fb3d5f71df118ca/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B2T2018%2Btype%40discussion%2Bblock%4034a8c20c84e14b01a7e56c5fb59c8c83

**Comment by petraBT** [comment]
@chrissmiller Could you add the prototype for the freeStudents function to the pre-populated code? I added it to the problem statement just now but I don't know where to find the pre-populated code. I am able to submit a solution without getting the error message the student reports, but it would still be good to include the prototype...

**Comment by chrissmiller** [comment]
Fixed!
