### ISSUE TITLE
trouble with paiement for Professionnal Certificate

### ISSUE THREAD

**Issue by Kitkatniss** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#310]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/course/threads/5bb7aa40b41e6e085b00024f

**Comment by mgoudz** [comment]
Payment issues should be addressed to edX learner support. Here's how I responded: 

Hello Levekesh,

You may be experiencing an issue with the edX payment system, which would need to be addressed by the edX Support Team. You can see this article about [Verified Certificate payments](https://support.edx.org/hc/en-us/articles/206502498-How-do-I-pay-for-a-verified-certificate-). If that doesn't address the problem you can "Submit a Request" to the edX Support Team. You can find that button at the bottom of that same page or by clicking Help in the top right corner.

You can continue to work in the course and your scores and progress will be saved and applied once the payment issues is resolved.

Thanks, Mike
