### ISSUE TITLE
1.0 suggestion for showing the special characters near the question (image recommended)

### ISSUE THREAD

**Issue by Kitkatniss** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#311]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/a755bfd83a8175beea1c18b52e4f843f7aa591b4/threads/5bb53ddcfb45b2082b000057

**Comment by klotsy** [comment]
pas une bonne idée car il n'auront qu'à faire un copier-coller...
ou alors une image, si ça tient...

**Comment by mgoudz** [comment]
@Kitkatniss if I'm reading your French comment correctly, you don't think this suggestion is worth implementing because it will give away the answer. Unless @remisharrock disagrees we'll close this.

**Comment by klotsy** [comment]
@mgoudz  the french comment it's me... Because here  the work is type the character, not to know the name of this, I think, to show the character can be a good idea if the student cannot copy-paste, therefore you should use a picture, not text
