### ISSUE TITLE
1.0 vocabulary, Ken Thompson mispelled in the quizz

### ISSUE THREAD

**Issue by Kitkatniss** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#312]
in this page under
Ken Thompson is mispelled

https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/33129229b7ae4999b57f03be444c2dd0/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%40bb214b4ed3e84f689a1914fbc7a6bb61

**Comment by petraBT** [comment]
fixed
