### ISSUE TITLE
1.0 vocabulary ; trouble with select/deselect ?

### ISSUE THREAD

**Issue by Kitkatniss** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#313]
See this message from the forum :

https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/a99d3f2a73bcbcb51394dcb4376fe2dabf767589/threads/5bb46fc63b0abc09ae00400e

**Comment by petraBT** [comment]
@Ella @Mike I corrected the typo in the quiz, but I don't know anything about the bug of not being able to de-select an answer. Could you look into that?

**Comment by mgoudz** [comment]
I could not reproduce the error. It may have been the learner had already used both attempts.
