### ISSUE TITLE
Activity bridge tax

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#314]
There is an extraneous comma in the text to print in the problem statement : 
"Regular tax," instead of "Regular tax"
Link to the activity : https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/a86febae1149479d971ae6edbd850c51/dd6988baae994fff80bd8bd9c1884cf4/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%402a4ff71898d840ab96b245d7adc87499
(Issue reported by a learner on the forum)

**Comment by mgoudz** [comment]
Direct link: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/a86febae1149479d971ae6edbd850c51/dd6988baae994fff80bd8bd9c1884cf4/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%402a4ff71898d840ab96b245d7adc87499

**Comment by chrissmiller** [comment]
Fixed!
