### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#315]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/994522d2b7fd30147c67f70b9e281652dcc9a863/threads/5bba567ab41e6e083d0003f4

Another one but I didn't get it?  
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/994522d2b7fd30147c67f70b9e281652dcc9a863/threads/5bba556bb41e6e08640003ec

**Comment by deladan** [comment]
Nat has rectified the second one.

**Comment by deladan** [comment]
Another one: 
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2018/discussion/forum/a082f8ad62848408c7e6c5a183c978214c2ba846/threads/5bbb9cd1fb45b2080f000557

**Comment by mgoudz** [comment]
Opening separate issues for each error so we can track these.

**Comment by mgoudz** [comment]
The third one is now in #326
