### ISSUE TITLE
6.2 Nothing's happening during nearly 20 seconds of the codecast

### ISSUE THREAD

**Issue by Kitkatniss** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#318]
Nothing's happening between 5'26 and 5'47 !

https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/953455675ecb40e491f6645e3711295f/0f6bc45e0328471ba775d27853a83b82/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40vertical%2Bblock%40c9ed72208f3f41098883390692671550

**Comment by remisharrock** [comment]
OMG indeed, it needs reediting !

**Comment by remisharrock** [comment]
I have a slow connection here this week and cannot work on that, I will try to do it when I'm back next week

**Comment by Shayes1740** [comment]
Issue resolved.
