### ISSUE TITLE
6.2 quizz typos in question 4

### ISSUE THREAD

**Issue by Kitkatniss** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#319]
4. If you are in your home directory (_**pwd prints**_ /home/user) what cd command should you write using a relative path to go to _**to**_ /sys ? (don't put a / at the end of your answer).

should be ?

4. If you are in your home directory ( /home/user) what cd command should you write using a relative path to go to  /sys ? (don't put a / at the end of your answer).

**Comment by Kitkatniss** [comment]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/953455675ecb40e491f6645e3711295f/e970653072f84df6bf457872dd3d2043/?child=first

discovering the file system  (by the way the title is written : filesystem)

**Comment by klotsy** [comment]
le to to oui, mais le pwd prints pourquoi l'enlever ?

**Comment by remisharrock** [comment]
yes we should remove to to but keep pwd prints

**Comment by remisharrock** [comment]
fixed
