### ISSUE TITLE
Trouble with input/output in examples

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#320]
In this thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/discussion/forum/8f87c9f6071a4290042f96417ab624eb16a96de4/threads/5bb906bdb41e6e0843000311, some learners complain about the fact that the given examples don't exactly show what should happen when we use the program in interactive mode.
I guess that these examples are displayed this way because of the first version of Codecast, used in the french mooc, with only split input/output mechanism.  
Maybe a message explaining how to choose this mechanism should be welcome here.  
I know that Petra and Rémi introduce it somewhere on the course, but I don't remember where, and by the way, the learners may not have taken all of the courses.

**Comment by petraBT** [comment]
Okay, I have done my very absolute best to make this example even clearer than it already was...
