### ISSUE TITLE
Taskgrader course 7 program arguments

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#322]
There seems to be an issue with this activity:
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+2T2018/courseware/b2fc63d70fe74a38963d1ddf871946b4/7be95ba870ea439c9bc94f21c7daa23c/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.07%2B2T2018%2Btype%40discussion%2Bblock%403b20449f9b604764ab90b0d5045024e0
error message :+1: 
1 Correction(s) (-5 points for each):
'cost' replaced with 'costs'

Issue reported by a learner on the forum. 
I guess that when there are several plants we should write cost instead of costs, but that's not the case in the given example.
EDIT : in fact that doesn't solve the problem...

**Comment by klotsy** [comment]
je confirme, tout se passe comme si il se lisait un cost (sans s) tout seul
si on met cost on a 
```
2 Correction(s) (-5 points for each):
'cost' replaced with 'costs'
'cost' replaced with 'costs'
```
et si on met costs on a 
![costs](https://user-images.githubusercontent.com/42912762/46600893-ea30eb80-caeb-11e8-82c5-8e63df2733d6.jpg)

**Comment by remisharrock** [comment]
@chrissmiller  est au courant merci de la remontée !

**Comment by chrissmiller** [comment]
Fixed!
