### ISSUE TITLE
confusing term

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#323]
A learner is not sure about the use of "behind" in the second question of this quiz:  
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/9afb1233a3d74a62acc1625236e57a96/dfe4caf70cdd417b912948810b3393e7/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2018%2Btype%40discussion%2Bblock%404fadc7abe8c743029e29ca7098c1919b
He'd rather expect after or beyond.

I'm not enough confident with english to take a stance here ;-)

**Comment by klotsy** [comment]
c'est un pinailleur ;-) et l'anglais n'est même pas sa langue maternelle en plus !

**Comment by mgoudz** [comment]
Fixed this. My response: 

deladan,

Thanks for the suggestion. You're right the phrasing is a bit confusing and we have updated it to **_following._**

Thanks, Mike
