### ISSUE TITLE
course 7.1 taskgrader using the jpeg library AND create and modify your own library AND 7.2 build a makefile

### ISSUE THREAD

**Issue by klotsy** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#324]
comme pour #289 taskgrader pénalise l'inversion
commande
`printf("gcc -std=c11 -Wall -fmax-errors=10 -Wextra vizplus.c /usr/lib/libjpeg.so -o vizplus");`
et même l'utilisation de eux espaces au lieu d'un avant le -o : 
commande
printf("gcc -std=c11 -Wall -fmax-errors=10 -Wextra /usr/lib/libjpeg.so vizplus.c  -o vizplus");
avec le même message	
message
```
You obtained a partial score. You can improve your program to get a better score.
Message from the evaluation :
It looks like your compiler command is in the wrong order - list the source code before the executable file name, separated by the -o flag. (-10 points)
```
seul `printf("gcc -std=c11 -Wall -fmax-errors=10 -Wextra /usr/lib/libjpeg.so vizplus.c -o vizplus");`
passe

**Comment by petraBT** [comment]
@chrissmiller Chris, this seems to be the same issue as the one you already fixed - could you apply the fix to these other tasks as well? Also, can you check on allowing two spaces in front of the -o flag?

**Comment by chrissmiller** [comment]
Revamped the checkers for these tasks; they will now accept the variety of possible orders and any amount of spacing between flags!
