### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by mgoudz** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#326]
Opening up a separate issue for this one originally reported in #315 

https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2018/discussion/forum/a082f8ad62848408c7e6c5a183c978214c2ba846/threads/5bbb9cd1fb45b2080f000557

**Comment by Kitkatniss** [comment]
Mooc 4

**Comment by chrissmiller** [comment]
Fixed thanks!
