### ISSUE TITLE
Unclear problem statement simple arithmetic activity

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#328]
In this activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccf660cc6a1141e0a9bebfc515ce320a/8886730e8869426bbdcab50815cbeedf/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%40448236f24ba64b4aa314ae93827ab3bd (course 1)
it is expected that the calculations are made by the computer itself, but I must admit that it isn't so clear in the problem statement:
"Warning: You cannot simply print the values - you must calculate them and print them using the %d format specifier."

**Comment by klotsy** [comment]
yes, "the program must" instead of "you must" ?

**Comment by petraBT** [comment]
Thank you! I attempted to make the problem statement more precise.
