### ISSUE TITLE
5.3 Activity: free a linked list of students ( related to #219)

### ISSUE THREAD

**Issue by klotsy** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#331]
@remisharrock  @petraBT  @chrissmiller 
Pour ne pas donner les solutions précédentes à chaque activité les énoncés ont été modifiés pour que l'apprenant mette ses propres fonctions - très bien
mais maintenant si on ne met pas exactement la déclaration qui était prévue avant on obtient l'erreur 
"Error - It appears you have modified restricted code."
exemple j'ai obtenu l'erreur en écrivant 
`void copyStr(char *s, char *t);` 
au lieu de 
`void copyStr(char *source, char *target); `
qui était la version donnée dans la correction avant la modification
(bien entendu j'ai correctement modifié la déclaration de la fonction...)

EDIT: NB cette fonction était à créer dans "Activity: append a node with student data"
on peut réutiliser sa propre définition sans problème dans "Activity: print a linked list of student data"

**Comment by klotsy** [comment]
@deladan @Kitkatniss quelqu'un peut traduire ? merci

**Comment by deladan** [comment]
The issue in update nodes is not exactly the same, but quite close, because in this case, function definitions are still provided.
But there is a slight difference in the line declaring the function append (a missing space between * and the name function) between the provided version and what the grader awaits.
There are some others but they don't seem to bother the grader (cf issue #103)

**Comment by deladan** [comment]
By the way, as all the other prototypes are provided, why not copyStr?

**Comment by klotsy** [comment]
je pense que les apprenants devaient trouver tous seuls qu'il fallait une fonction pour copier la chaîne - dans le code fourni il y a
"`// Write other function prototypes here (if any)`"  et si on leur donnne le prototype dans une autre activité ensuite c'est presque leur donner la solution

**Comment by petraBT** [comment]
I cannot seem to be able to reproduce the error mentioned by @klotsy. I replaced my copyStr() prototype with the one mentioned (void copyStr(char *s, char *t);) but I still don't get the error. @klotsy could you send the entire code that you submitted so that I can take a look?

**Comment by deladan** [comment]
It's not the prototype which causes problem, but the definition of the function.  
We have to use the same names for the parameters.

**Comment by petraBT** [comment]
Ah! Yes, I was finally able to reproduce the error! @chrissmiller, if I take the sample solution and replace the function definition of copyStr() with the following, for example, I am told that I have modified restricted code. Is this sufficient info for you to track down what's happening?

void copyStr(char *s, char *t) {
    int i = 0;
    while (s[i]!='\0') {
        t[i] = s[i];
        i++;
    }
    t[i] = '\0';
}

Even if I go back to the original variable names but replace int i = 0; with    
 int i;
 i=0;
I get the same error.

**Comment by klotsy** [comment]
yes, idem if I replace i++; par i=i+1;

**Comment by chrissmiller** [comment]
Managed to track it down and fix it - just some leftover checking from before we changed the structure to have the student re-implement all those functions!
