### ISSUE TITLE
Not enough tests in Taskgrader

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#334]
A leaner has drawn attention to the fact that in the activity about monitoring a chemical experience, Taskgrader accepts codes that don't do the job.  
Surely some tests to add to it.  
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/discussion/forum/a72c02975d539216f42f9db112a729271a6c6bf4/threads/5bbf4b60fb45b208370007b7
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/c994b80204d747b6aa16ad991f4b1904/bcaeeafdf43b417e910a6ac07da4bd83/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%40c91e5d9883c54d3b841c578776d54f91

**Comment by petraBT** [comment]
I am clearly no good at this Github thing. @chrissmiller please see my comment in #339...

**Comment by chrissmiller** [comment]
Going to close this just so we can consolidate into one issue (#339 )
