### ISSUE TITLE
There are no tests for this task.

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#335]
Several learners reported having run into this message on different Taskgrader activities.  
Solution seems to be refreshing the page and resubmitting.  
An idea about that?

**Comment by klotsy** [comment]
I'ts the same for me, no idea

**Comment by chrissmiller** [comment]
I have contacted Michel, hopefully he can track down the issue!

**Comment by chrissmiller** [comment]
Should be resolved now! It was due to a server disk issue that Michel has corrected.
