### ISSUE TITLE
5.3 Subtitles missing for Codecast Search for a node in a linked list

### ISSUE THREAD

**Issue by Kitkatniss** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#337]
No subtitles for this Codecast :
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/courseware/ec78e06b33f444cb8265d8c58227da98/58db2f5a71e44f1abc7316ed9ce1cd74/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B2T2018%2Btype%40vertical%2Bblock%40e8a8fdff269242a7a18a8388e6e16e2b

**Comment by klotsy** [comment]
il ne reste plus que celui-ci à relire ! existe-t-il ?

**Comment by EllaHa** [comment]
You are right! This codecast was actually missing from the subtitle batch. I have just required a transcription. We will have to wait for a few days.

**Comment by EllaHa** [comment]
Here it is! (please refresh your cache)

**Comment by klotsy** [comment]
thanks, relecture en cours :-)
