### ISSUE TITLE
Issue with the last activity?

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#340]
I've tried to submit my code, but it wasn't accepted by the grader, which seems to find only the last number written in the file myGrades.txt after the program ran.  
I've investigated a little further, and I realized that my file myGrades.txt contains a new line before the next number. 
Indeed, I've created the file with echo without the -n option, and it's normal things was written in a new line while using the mode "append".
(By the way, same thing if I create the file using vim or gedit, it appears that a newline is automatically added at the end of the file).
As everything goes well on my computer once this corrected, I'm wondering whether your file myGrades.txt hasn't a new line also and whether the grader checks only the last line of this file.  
But maybe I went totally the wrong way here (sorry about my lack of experience and for bothering you if it is the case).  
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+2T2018/courseware/b2fc63d70fe74a38963d1ddf871946b4/da94b90a903d4495bb0f1d0ffff513b0/
My code:

#include <stdio.h>

int main() {
    int lastGrade;
    scanf("%d", &lastGrade);
    
    FILE * myGrades = fopen("myGrades.txt", "r");
    int readGrade;
    
    while(fscanf(myGrades, "%d", &readGrade ) == 1) {}
    fclose(myGrades);
    
    if (readGrade != lastGrade) {
        
        myGrades = fopen("myGrades.txt", "a");
        fprintf(myGrades, " %d", lastGrade);
        fclose(myGrades);
    }
    
    myGrades = fopen("myGrades.txt", "r");
    
    while (fscanf(myGrades, "%d", &readGrade) == 1){
        printf("%d ", readGrade);
    }
    fclose(myGrades);
    return 0;    
}

Thanks!

**Comment by deladan** [comment]
Obviously, I don't know how to post code on GitHub...

**Comment by deladan** [comment]
By the way, when I test my program on (in?) weblinux, when appending a new number to the file, there are some dots in red which appear at the end of the file that I don't understand.
![capture d ecran de 2018-10-12 07-32-33](https://user-images.githubusercontent.com/34571147/46849740-3aac8f80-cdf1-11e8-8a32-cbb67ab91add.png)

**Comment by petraBT** [comment]
Oh, I just encountered a similar issue which I believe goes back to the same underlying problem (issue 341 - not sure how to link an issue here). I too am bad at posting code... @chrissmiller I think this is another manifestation of the needed "file reset". If such a reset is not possible we need to rethink the problem statement in order to force the reset. Let me know, Chris?

**Comment by chrissmiller** [comment]
This should be good since the file reset is now working properly as done in #341 !
