### ISSUE TITLE
7.3 write numbers to a file needs a file re-set

### ISSUE THREAD

**Issue by petraBT** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#341]
If a student accidentally garbles the file from which they are reading (and to which they are supposed to append) then they cannot recover from this error even if subsequent submissions are correct.

This can easily happen if for example they open the file for writing instead of appending. Here is another way in which I was able to "destroy" my input file for good: simply add these lines to the top of the correct solution:

`	ifile = fopen("myGrades.txt", "w");
	fprintf(ifile, "90 88 84");
	fclose(ifile);
`
@chrissmiller is there a way to reset the input file for each submission?

**Comment by chrissmiller** [comment]
Hi @petraBT - I am looking into this. Right now the checker does have a statement which resets the file, so I am not completely sure what is wrong with it/why it isn't working. Will update you as soon as I have an answer/fix!

**Comment by chrissmiller** [comment]
All fixed! Should reset it properly moving forward.
