### ISSUE TITLE
Issue with using IDE and activities with provided code?

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#342]
A learner ran into a problem while using an IDE whose formatting isn't the same than Taskgrader, and hence copying/pasting makes taskgrader thinks the restricted code was modified.  
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2018/discussion/forum/4b630d5e10e414daff93349ef8098528b993f4d9/threads/5bbe8f35b41e6e081a0007e7

I don't know if there is something to do about that...

**Comment by remisharrock** [comment]
I replied, thank you for reporting !
