### ISSUE TITLE
"wrong" solution for the find the minimum of a list activity

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#344]
A learner reports that the given solution won't work with a list with only one number.  
Link to the activity:  https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/9afb1233a3d74a62acc1625236e57a96/07d4663586b74bd6abd7b94bf3326474/6?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2018%2Btype%40discussion%2Bblock%409e7dd39b807b452b8570729368aea7fd

I didn't actually proceed the way your solution does. I first read one number and assigned its value to a variable minimum, and then I actualized this minimum with each number.  
This should fixed this issue, shouldn't it?

My code:  

```
#include <stdio.h>

int min(int, int);

int main(void) {
	int i;
	int minimum ;
	int nb ;
	int readNb;

	scanf("%d", &nb);
	scanf("%d", &minimum);
	
	for (i = 1; i < nb ; i++) {
		scanf("%d", &readNb);
		minimum = min(minimum, readNb);
	}
	printf("%d\n", minimum);
	return 0;
}

int min(int a, int b) {
	if (a < b){
		return a;
    }else{
		return b;
    }
}

```

**Comment by petraBT** [comment]
Wow - these learners are really paying attention! I just updated the solution.

**Comment by EllaHa** [comment]
@petraBT do we need to update users attempts?

**Comment by EllaHa** [comment]
@petraBT sorry this is a taskgrader so my comment is irrelevant!
