### ISSUE TITLE
Use of 'const' in a solution

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#345]
In the given solution for the activity about the smart unit converter, const is used, but as a learner remarks it on the forum, I'm not sure it was introduced before in the course.  
This learner also complains that that shouldn't be used here because later than ANSI C, but I don't agree with him.
Someone could confirm that?
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/discussion/forum/022af50ca31fe27dc07df110a366aea6a28df050/threads/5bc263f8b41e6e0861000a7a
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/9afb1233a3d74a62acc1625236e57a96/07d4663586b74bd6abd7b94bf3326474/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2018%2Btype%40discussion%2Bblock%407122ea906669412b907fdb23bc26c0da

**Comment by petraBT** [comment]
I deleted the "const" operator from the sample solution. While I was at it I also cleaned up the problem statement a bit.
