### ISSUE TITLE
unclear problem statement (find the minimum)?

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#346]
A learner complains that the problem statement doesn't mention that we have to write a prototype.
I think he or she has defined the function before the main function, as it is possible to do.  
I don't think that this option was introduced in the course though.  

Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/discussion/forum/11ba11ebe81fe8548b4bba61b4a260e337947812/threads/5bc2680f4265a4091a0008e2
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/9afb1233a3d74a62acc1625236e57a96/07d4663586b74bd6abd7b94bf3326474/6?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2018%2Btype%40discussion%2Bblock%409e7dd39b807b452b8570729368aea7fd

**Comment by petraBT** [comment]
I added the prototype requirement to the problem statement.
