### ISSUE TITLE
3.2 activity programming a toaster - vagueness in statement

### ISSUE THREAD

**Issue by klotsy** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#347]
the statement do not says if 0 KB must be print or not when the size is > 1000000<br>
for example 4000004 : <br>4 MB and 0 KB and 4 B _or_ <br>
4 MB and 4 B<br>
Taskgrader accepts both versions of code...

**Comment by chrissmiller** [comment]
I think this should be pretty clear from the example which shows an output with nonzero MB/KB and zero B but have added an additional check to make sure that grading reflects that, thanks!
