### ISSUE TITLE
Issue with subtitles in a codecast from unit1.1

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#349]
The subtitles for the first codecast about comments aren't available.  
Link to the codecast: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/6e554ffe0eb345c4a343a63b4f436db5/67d05789483a44bf8c3b095b974c188a/

**Comment by EllaHa** [comment]
Hi David, any clue why there was a special character added at the end of the srt file? Maybe when we copy paste file from framapad. Not sure why this is happening.
![image](https://user-images.githubusercontent.com/19490273/47006516-5fc53900-d136-11e8-94b3-d0868af61768.png)
This has been fixed. If you empry your cache you wil see the subtitle

**Comment by deladan** [comment]
Hello!
I'm afraid I am the guilty one.  
When revising subtitles, I use vim and I must have typed this sequence of characters (normally to close vim) while still in insertion mode.
Sorry for that!
