### ISSUE TITLE
typo in quiz about interactive programs

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#351]
Second question: the file otherans is mispelled othercans in the "correct" answer.
That was reported earlier by a learner in the forum, but I didn't understand the message when I first read it, sorry about that. 
By the way, in the same thread, another student complains about the fact that we weren't told before about redirections (I suppose?). Maybe someone from the team might answer him?

Link to the quiz: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/632a112f8d4e46c88cf195f34e486a4f/7c1d9bb1804444f092456eeeecb8cffd/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40discussion%2Bblock%4064bda04351f749b8b15051f67feefd29
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/discussion/forum/1f44302aa86f579c6b696591b6a8a7d5208d057e/threads/5bbcb4454265a40902000691

**Comment by EllaHa** [comment]
Thanks Isabelle for reaching out. 
@remisharrock should we change the correct answer? 
Should I reset learners attemps for this question?

**Comment by EllaHa** [comment]
Thanks Isabelle. Rémi confirmed the typo, I have reseted learners attempts on this question.
