### ISSUE TITLE
issue with update node

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#352]
This issue is related to the #267 one, but wasn't fixed yet, and some learners are in difficulty here.  
The provided code differs from what is expected, causing Taskgrader to reject the code saying we've modified restricted code.  
I've checked all the differences between this provided code and the solution. There are quite a few of them, but the only one which get us stuck is the missing space between `*` and `append` in the definition of the function `append`.
Can't that easily be fixed? Just adding a space in the provided code?

**Comment by remisharrock** [comment]
@chrissmiller same as #267

**Comment by chrissmiller** [comment]
Should be all set now so sorry for the delay!
