### ISSUE TITLE
error in an example in the activity "read numbers from a file" course7

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#360]
Some learner made the remark that the last output which is displayed as example in the problem statement is erroneous.  
It should be 74.57 rather than 75.57.  
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+2T2018/courseware/b2fc63d70fe74a38963d1ddf871946b4/c69c696065964550835dcade17e8e61a/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.07%2B2T2018%2Btype%40discussion%2Bblock%4096ebca3fd3bf4db08145d6ce13b2adab

**Comment by EllaHa** [comment]
Thanks Isa. 
@petraBT @remisharrock can you confirm this?

**Comment by EllaHa** [comment]
learner's attempts should be reseted after edition

**Comment by deladan** [comment]
The issue affects only the example, and not the grader.  So it isn't a grading issue and I don't think you'll have to reset attempts then.
Moreover, we have as many attempts as desired ;-)

**Comment by petraBT** [comment]
Than you, @deladan ! I just fixed the example.

**Comment by EllaHa** [comment]
@deladan great! so I am not doing anything regarding grading!
