### ISSUE TITLE
A learner proposition for enhancement of the activity about youth hostel

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#361]
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/discussion/forum/107ef9fff279e358b2aebadca69fca50667661a5/threads/5bb9b02cfb45b2083a00039f
Look at wangziyu1993's comment.

**Comment by petraBT** [comment]
Okay: I clarified the problem statement - hopefully this will be 100% unambiguous!

**Comment by deladan** [comment]
Actually, wangziyu1993 was suggesting to make the problem a little more complicated, including morning arrivals (if I correctly understood him or her).  
I've just reported his/her comment, that doesn't mean I necessarily agree with him or her.
