### ISSUE TITLE
Irrelevant suspicious warning from Taskgrader

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#364]
Course 1, some learner has got a warning from Taskgrader for using suspicious if statement.  
But if statement isn't introduced in this course, and this learner hasn't used one.  
It appears he/she just named one of his/her variables "ifuture", misleading Taskgrader.  
Something to do do about this, in order not to confuse beginners?
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/28fd6ca99ec21869dd7be0eb1a838e81a68fbf8a/threads/5bc6fcd24265a408ff00126c

**Comment by chrissmiller** [comment]
Hmm... Thanks - I have removed the check for this, since if statements haven't been introduced yet. Will try to think what the best way to improve the check is - possibly looking for if with a parenthesis or space afterwards instead of just if alone...
