### ISSUE TITLE
mooc 1 subtitles are misssing  now ??

### ISSUE THREAD

**Issue by Kitkatniss** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#366]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/994522d2b7fd30147c67f70b9e281652dcc9a863/threads/5bc770524265a408ff00130c

https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/994522d2b7fd30147c67f70b9e281652dcc9a863/threads/5bc33c44b41e6e082f000b35

**Comment by deladan** [comment]
For the second one, the issue has been fixed.
There were some extra characters in one of the lines indicating the time (and I'm afraid I was the culprit) that prevent the file to be used as subtitles.  
But I can't see any such issue for the proposition we made for codecast about finding the remainder.
Here the link to it: https://bimestriel.framapad.org/p/u3-1_cc_remainder

**Comment by EllaHa** [comment]
https://github.com/France-ioi/codecast/issues/132

**Comment by EllaHa** [comment]
Fixed please empty your cache
