### ISSUE TITLE
quizz

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#37]
Which course: 1 Getting Started What type of content: quizz URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/33129229b7ae4999b57f03be444c2dd0/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40vertical%2Bblock%40a50ac79eeff9493fa2e9be7f434d0774 Description: in  Activity: vocabulary   I think there's an error in the quizz : according to your video  a mouse pad is a hardware elements but in the quizz it is not accepted. other comments: PS: I think hardware is an ambiguous word. Better talk about peripheral devices and core computer hardware components your name: Godefroy screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel:

**Comment by EllaHa** [comment]
a mouse pad is not considered "hardware"
