### ISSUE TITLE
Issue with grading in the activity about chemical experience

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#370]
Achieving this activity doesn't systematically give us a maximal score.  
i've been assigned a 0.02/1, and some learner 0.8/1.  

Maybe only the first score was reported to the edX platform in this activity, and not the best one?

![capture d ecran de 2018-10-20 05-32-18](https://user-images.githubusercontent.com/34571147/47250855-ab732d80-d429-11e8-8cfa-c9a35407ca23.png)

Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/c994b80204d747b6aa16ad991f4b1904/bcaeeafdf43b417e910a6ac07da4bd83/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%40c91e5d9883c54d3b841c578776d54f91

**Comment by deladan** [comment]
Hello!  
Today, I'm inexplicably granted 1.0/1.0.
But it seems that the problem remains for some learners.
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/discussion/forum/a72c02975d539216f42f9db112a729271a6c6bf4/threads/5bc9e5baef5b3309c20001af

**Comment by catherinechoww** [comment]
After testing with the above code, I got 100%, so it seems to be fixed. No users have complained about this since then, so closing the issue.
