### ISSUE TITLE
Posting code on forums

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#371]
Given the great number of ill-formatted codes in the forums, it seems that learners don't follow the given link to the wiki.  
I'm wondering whether the instructions shouldn't directly appear in the course, within this section: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/e4ee673e89a9468ebd5a0d66d608db29/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40vertical%2Bblock%40a4c7203ecb4a405a83dc8068f00a6b4c

**Comment by deladan** [comment]
AntAug just wrote a tremendous tutorial message that I've pinned on the forum of course 1.  
Maybe it should be added to the section of each course.  
Link to the post: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/0063cd62a6156198d8a3d3de05c6ac9d971a2ad8/threads/5bcc9e2136101309b6000412

**Comment by catherinechoww** [comment]
Tutorial has been pinned on the top of every MOOC's discussion forum.
