### ISSUE TITLE
Not enough tests?

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#373]
In course 1, activity about robots, Taskgrader tests the program only once.  
So a program whose only instruction is to print 163 is assigned a 100% score...
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccf660cc6a1141e0a9bebfc515ce320a/76cd4b61bfd641de982b5f4f9a169ee6/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%4002bc7c036e874cd4b15818185a8d1c2e

**Comment by chrissmiller** [comment]
Fixed!
