### ISSUE TITLE
Not enough tests (again)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#375]
In the activity about costly hotel rooms, course 1, a program will print out 0 for an age greater than 60 is accepted, whereas it should be free only when age is exactly equal to 60.
It appears also that adding 10 whatever the luggage's weight is accepted as well.
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/a86febae1149479d971ae6edbd850c51/fc9008c149444ca0a623cc332fc01e06/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%40f5755cb0e797445082dce25b9fd57193

**Comment by chrissmiller** [comment]
Thank you, fixed these two issues and an issue where it wasn't checking the age under ten condition!

**Comment by chrissmiller** [comment]
Fixed :)
