### ISSUE TITLE
ill-formatted command in quiz (course 6).

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#382]
A detail, but in the question 6 of the quiz about Linux and the files, the mount command isn't formatted as code as other commands are on the quiz.  
It seems to have confused a learner who didn't understand the question.  

Link to the quiz: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/953455675ecb40e491f6645e3711295f/0f6bc45e0328471ba775d27853a83b82/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40discussion%2Bblock%4077b4b5e2b6c24fcf91eeb945d5043735

**Comment by petraBT** [comment]
Fixed.
