### ISSUE TITLE
Confusing problem statement of the activity about swapping first name and last name (course 2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#386]
I know some issue was already opened about that but I can't find it anymore, sorry about that.  
Learners still complain on the forum about the examples in this activity, which suggest that we have to read all the input first and then treat them.  
I don't know of a good way to present things, but I guess that some hint, as "Treat each name one after the other", could be added to the problem statement.
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/f2a41407085b4e8c8a5604123388ef33/914396655d9144bfaf7bd9710bc7415e/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%4014f2b324a7ea47868093d86f2d627272

**Comment by chrissmiller** [comment]
This has been addressed!

**Comment by deladan** [comment]
I suppose problem is that learners don't carefully read problem statement ;-)
