### ISSUE TITLE
Some issue with the activity about updating nodes (course 5)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#388]
The grading issues regarding this activity have been fixed, but the given code in the problem statement hasn't been actualized.  
However some learners may want to copy it and use it on their computer, rather than directly working on Taskgrader, and when they paste it, it won't be accepted without modification.  

Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/courseware/ec78e06b33f444cb8265d8c58227da98/58db2f5a71e44f1abc7316ed9ce1cd74/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B2T2018%2Btype%40discussion%2Bblock%40779a6f9951374117a98c2dd2629d6e88

**Comment by chrissmiller** [comment]
Fixed!
