### ISSUE TITLE
Grammatical issue (course 6)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#389]
Reported by some learner on the forum about the quiz on Linux genesis:

> The answers to Q2 should all be in the past tense:
> 
>     because he was dissatisfied...
>     because it disagreed…

Link to the quiz:  https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/fa3b199b4927423f90a0f80550b0d4c3/e241fa2b0ca1495db74ce4c94b47820d/7?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40discussion%2Bblock%400818d3c0c1d24139a80adf315ef07c8f

**Comment by petraBT** [comment]
Fixed.
