### ISSUE TITLE
Some suggestions for the quiz about Linux and files

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#391]
Some learner found confusing the way folders are displayed in the question 9.  That could indeed suggest that the name of the folders are "a popular folder" and so forth.  

By the way, he also suggest to modify the word "good" in the expected answer by "right" or "proper".  

Link to the quiz: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/953455675ecb40e491f6645e3711295f/0f6bc45e0328471ba775d27853a83b82/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40discussion%2Bblock%4077b4b5e2b6c24fcf91eeb945d5043735
Link to the thread: 
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/discussion/forum/c897d7ccc938325e4b81d07e9929c7c7328dc8b2/threads/5bd1e41a36101309b60009be

**Comment by petraBT** [comment]
Fixed.
