### ISSUE TITLE
Misleading hint on the activity about creating node (course 5)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#393]
Some learners reported that they don't find where in the course we've written a copyStr() function.  
One of them has even looked for it in all the previous courses.  

Yet the hint for this activity suggests that we reuse it here.  

I didn't find it neither, but I must admit I didn't spend a lot of time looking for it.  
So either it is actually somewhere in the course and I think it would be a good idea to specify where in the hint, either we didn't see this function before and the hint should be modified.

Link to the activity:  https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/courseware/ec78e06b33f444cb8265d8c58227da98/f6fb8040b1214d258cba7629aa06730e/2?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B2T2018%2Btype%40vertical%2Bblock%40cbd29599deed45ebae6968859b570567

**Comment by chrissmiller** [comment]
Hmm I am not sure where it went - it was originally in some of the codecasts/videos I think but may have been removed. I've updated the hint regardless to suggest that users create the function as a good learning opportunity!
