### ISSUE TITLE
Missing precision in the activity "program a smart unit converter" (course 3)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#396]
Some learners made the remark that using float will give different results than the one expected.  

As this type is introduced later in the course, learners shouldn't be tempted to use it, but I suggest that you say at this time that the type double is the one to use for the activities.  

Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/9afb1233a3d74a62acc1625236e57a96/07d4663586b74bd6abd7b94bf3326474/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2018%2Btype%40discussion%2Bblock%407122ea906669412b907fdb23bc26c0da

Link to the Codecast where float type is introduced (and where I'd add a remark precising double will be rather used): https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/5c40ed165b45423496c1c8c8fdca08d9/91f8edcd857f410b82baa1860866f4ae/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2018%2Btype%40vertical%2Bblock%408048e21619614947871d6cd87cac5e33

**Comment by chrissmiller** [comment]
Added!
