### ISSUE TITLE
Some lack of consistency with gcc option (course 7)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#397]
Some learner remarks that the use of the -std=c11 option for gcc in the course is not very coherent with the purpose of this course which is to teach us ANSI C.  

Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+2T2018/discussion/forum/ab4624ae490e2b2c7589f718b60f2c26c6a031c8/threads/5bd7006aef5b3309aa000bad

**Comment by chrissmiller** [comment]
@petraBT @remisharrock What are your thoughts on this? Happy to change it if you agree

**Comment by petraBT** [comment]
Hmmm... I do agree but then on the other hand we never explain these options anywhere, do we? Maybe in a future iteration of the course we should explain these switches and then also pick a lower standard? But since we use c11 in our videos I don't think we should change this now in the exercises?

**Comment by chrissmiller** [comment]
Good point - I think we should keep it consistent with the videos if c11 is the standard used there since students may just try to emulate what is done in the videos.
