### ISSUE TITLE
Personal feedback about the activity : Allocate memory for strings (course 4)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#398]
In this activity, we're asked to call the function allocateString() with an argument equals to length + 1 for the null terminator.  
Wouldn't it be more consistent that the function itself deals with granting enough space for the string the user wants, and don't count on him/her to think about this null terminator?

Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2018/courseware/26662efa0f944539bb7015cfd95bff18/c07dad218ea24b1b888d929392e30c6d/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.04%2B1T2018%2Btype%40discussion%2Bblock%4047e3625ef7d84263b64c34058484318a

**Comment by chrissmiller** [comment]
Great point - I have altered the provided code and solution to incorporate your suggestion. Thank you!!
