### ISSUE TITLE
Vocabulary issue on the quiz about compilation (course 6)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#399]
Some learner has difficulty with the expression "inverted number" (question2), and suggest something like "reverses the order of the digits" instead.  

Link to the quiz: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/632a112f8d4e46c88cf195f34e486a4f/5a68ec5063644f41986eb24655613ab1/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40discussion%2Bblock%4055c7da0e5e9244ab9c8066477df744e3

**Comment by petraBT** [comment]
Fixed.
