### ISSUE TITLE
joke

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#40]
Which course: 1 Getting Started What type of content: joke URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccb75017dce84804a4477600cf09014d/91cbe11e73bc44c0aa6b5dad1e83c46e/?child=first Description: Comparing this exercice with Fun Mooc   I like how the exercice subject was changed :p other comments:  your name: Kitkatniss-Cat screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel:

**Comment by Kitkatniss** [comment]
close this

**Comment by EllaHa** [comment]
Glad you liked it!
