### ISSUE TITLE
weblinux and firefox

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#400]
As for the french mooc, there is some issue with weblinux running on Firefox.  
It works perfectly and then some day, doesn't correctly start.  

The only way I've found was to wipe data from sites on the navigator, but that may seem brutal.  
By the way, this issue doesn't seem to occur with Chrome.  

A link to some learner's report of this problem, with a screencast: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/discussion/forum/8d5d51c36cf6b90686ddc57cc8d5fba67ecc4437/threads/5bd9be723610130971000bfa

**Comment by EllaHa** [comment]
Thanks @deladan  for reporting this @natjhealy shall we had this problem to the FAQ

**Comment by natjhealy** [comment]
Looks like David already took care of this. Detailed instructions are now on the FAQ page.
