### ISSUE TITLE
Misleading indication in problem statement (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#401]
I'm afraid I've already write an issue about this topic, but I can't find it anymore.  And there is some feedback on the forum about it.

In the activity Divide decimals of the section Practicing division, we're asked to read numbers up to 2 decimals.  
Learners have been tempted to use the %.2lf format specifier as with printf but it isn't accepted by scanf.  
I don't know of a way to do that, and I don't think it has been introduced in the course.  
And as we're expected to output an integer in this activity, I find this precision is quite misleading.  
Shouldn't this (to 2 decimals) been removed from the problem statement?

Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccb75017dce84804a4477600cf09014d/4c4f062124eb47f99ab23cf7228a1109/?child=first
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/db1c5a544b63f0b30ca7993d14e817bfd790a82a/threads/5bbcaadbb41e6e085e0005ee

**Comment by chrissmiller** [comment]
Hmm, no idea why that was there. Fixed!
