### ISSUE TITLE
Issue with the solution of the activity about robots

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#402]
Some learner pointed out that the given solution couldn't be run in Codecast, because of the presence of '\n' in a scanf instruction.
He also remarks that the variable "resistance" has been named "coefficient". Certainly some remainder from the french version ;-)
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccf660cc6a1141e0a9bebfc515ce320a/76cd4b61bfd641de982b5f4f9a169ee6/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%4002bc7c036e874cd4b15818185a8d1c2e

**Comment by chrissmiller** [comment]
Fixed, thank you!
