### ISSUE TITLE
typo in an hint (course 2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#403]
In the hint of the activity: find the longest word, the null character is said to be '\n' instead of '\0'.  

Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/f2a41407085b4e8c8a5604123388ef33/cf7f6546fc4d411992a1d434b489a916/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%409c0b79b95174489c86727bc85956fcad

**Comment by chrissmiller** [comment]
Fixed, thanks!
