### ISSUE TITLE
Issue with a solution of the activity "Update nodes in a linked list"

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#404]
If one tries to submit the given solution, Taskgrader rejects it saying restricted code has been modified.  
This solution doesn't seem to have been actualized since initial issues on this activity were fixed.  

Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/courseware/ec78e06b33f444cb8265d8c58227da98/58db2f5a71e44f1abc7316ed9ce1cd74/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B2T2018%2Btype%40discussion%2Bblock%40779a6f9951374117a98c2dd2629d6e88

**Comment by chrissmiller** [comment]
Fixed, thanks!
