### ISSUE TITLE
"suspicious" for loop in the solution of Tug of war

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#406]
Solution of activity Tug Of War, unit 2-1: `for(int i=0 ; i<nbMembers ; i++)`
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/a86febae1149479d971ae6edbd850c51/dd6988baae994fff80bd8bd9c1884cf4/5?activate_block_id=block-v1:Dartmouth_IMTx%2bDART.IMT.C.02%2b1T2018%2btype@discussion%2bblock@ea1d9b78328042169dfef7e52f25434f

**Comment by chrissmiller** [comment]
Whoops, thanks, fixed the non-ANSI compliant solution
