### ISSUE TITLE
Activity

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#41]
Which course: 1 Getting Started What type of content: Activity URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/6e554ffe0eb345c4a343a63b4f436db5/1ddcf56c5704415d864b3c5a8f24b86a/2?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40vertical%2Bblock%405563e751ed1c4bd88dd246681189f16e Description: In  Activity: put lines in the correct order   if you put  print( I  )   before  int i   it is not accepted but it is correct (even if not good practice). other comments:  your name: Godefroy screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel:

**Comment by deladan** [comment]
A learner just made the same remark on the forum: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/38082827aefcad86a793c96bea934940ffc07a00/threads/5bb4a3b6c305ad0a16004001

**Comment by chrissmiller** [comment]
I think this is okay with the updated description, especially since (I believe) we are teaching ANSI C in which this is not valid.
