### ISSUE TITLE
Over-complicated solution of the activity about carpooling (course 2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#410]
I (and participants in the forum) find the calculation of the amount we've got to pay if there are passengers quite complicated.  
`totalCost/(nbPassengers+1)` will suffice, won't it?  

Link to the activity:  https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/a86febae1149479d971ae6edbd850c51/e7f149c2d6c640cd8f5b9c36ae72437c/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%40a3d4c45ed15c405db6edc64215294f2d

**Comment by chrissmiller** [comment]
Thanks, fixed!
