### ISSUE TITLE
rewording some quiz question (course6)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#411]
Some learner complains that the first question of the quiz about find and locate is ill-worded, as we're looking for a 14-character long name and not a 14-letter long name.  

Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/discussion/forum/f184227962fcb2524e225b14f99685ca5d79d2d1/threads/5bfa2a684fc23009fb001390
Link to the quiz: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/953455675ecb40e491f6645e3711295f/2cd1aef12a4147dba381e83e10a44580/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40discussion%2Bblock%406c9873d6cbe7449aa00b59f89b9f7d63

**Comment by petraBT** [comment]
Fixed!
