### ISSUE TITLE
A typo in the activity about ingredients (course 2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#414]
One participant on the forum reported a typo in the problem statement.  
"up to a maximum of 10 integers" should be replaced by "up to a maximum of 10 ingredients", or  "up to a maximum of 10".  
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/c994b80204d747b6aa16ad991f4b1904/7274ebb9203b4dc5ac1dd1581089f3be/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%40f656c6f89b2f439288dfe3aba7ba2701

**Comment by chrissmiller** [comment]
Whoops fixed this awhile ago but forgot to close the issue!
