### ISSUE TITLE
Issue with a test on Taskgrader activity: find repeated letters (course 2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#416]
The second test seems to be false, as solution doesn't validate it any longer.  
By the way, some learner wrote a program which count iteration several times if the letter is repeated more than three times in the word.
I mean that an input as "aaaabc" has output 2 instead of 1.
But its program behaves correctly if there is no more than 3 repetitions: "aaabc" gives the expected 1.
I guess that we can't test everything, but maybe you could add (or modify) some test providing it a word with more than 3 repetitions of the same letters.
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/f2a41407085b4e8c8a5604123388ef33/b32dae4bf4454a179f4cece1403ab0e2/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%4079f7708322cc448ab739c65c846aab34

**Comment by petraBT** [comment]
Thank you for reporting this - should be fixed now. As for the learner who'd like to count more than 2 occurrences of the same letter multiple times: that would be a different problem to solve. As it stands, our problem statement is clear that this should only be counted once. Thanks!

**Comment by deladan** [comment]
What I meant is that his program was accepted even if it doesn't do what is expected, so I was just wondering whether more tests should be added.

**Comment by petraBT** [comment]
Oh, I see. Thank you! @EllaHa @mgoudz @remisharrock this can easily be fixed by adding another test (or simply modifying an existing test) - but then the student with the incorrect code would no longer receive full credit (but hopefully they wouldn't re-submit and so not trigger anything?). What do you think: is this something do be done now or an improvement for the next version?
