### ISSUE TITLE
Some complaint about the quiz cat less more (course 6)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#417]
Some learner asks why the answer `rm -r my file` isn't considered as correct, as the option -r let rm also work on files due to its recursive nature.  
Link to the quiz: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/953455675ecb40e491f6645e3711295f/a7169c56bd0d42a5a61f14e521b195ad/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40discussion%2Bblock%408269fd6ee011487fb31fb6be6dcf4781
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/discussion/forum/9770d1c0972edf1124b27ca4a6a23d1c08fb8673/threads/5c073cde4fc2300a130019fc

**Comment by deladan** [comment]
Another learner complains about this issue: 
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/discussion/forum/9770d1c0972edf1124b27ca4a6a23d1c08fb8673/threads/5c8027c7db70a9098a0038c0

**Comment by deladan** [comment]
another complaints: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/discussion/forum/9770d1c0972edf1124b27ca4a6a23d1c08fb8673/threads/5e0b5f3d7febe5096700256f

**Comment by remisharrock** [comment]
we have to fix that for v2 @AadhyaKocha @Eli-Boardman 
let's change rm -r my file with
rm -r my\ file

**Comment by Eli-Boardman** [comment]
Updated as per Remi's comment
