### ISSUE TITLE
bad numbering of units on forum (course 4)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#426]
On the forum of course 4, the section "Introduce yourself" is marked as Unit 3.0.  
![capture d ecran de 2018-12-10 05-02-09](https://user-images.githubusercontent.com/34571147/49710358-2b06c700-fc39-11e8-8f8b-5bd4ed1938b5.png)

**Comment by EllaHa** [comment]
Thanks this is fixed
