### ISSUE TITLE
Issue with provided solution in activity "Create a student list" (course 5)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#428]
Provided solution isn't accepted by Taskgrader which says that restricted code was modified.

Indeed, in the main function, the variable myAge is initialized to 25, whereas in the provided code, it isn't initialized at all.

Link to the activity:  https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/courseware/ec78e06b33f444cb8265d8c58227da98/f6fb8040b1214d258cba7629aa06730e/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B2T2018%2Btype%40discussion%2Bblock%4014e3acd162a44138b10a7a427b1ef8b7

**Comment by chrissmiller** [comment]
Fixed, thank you!
