### ISSUE TITLE
Confusing problem statement (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#429]
In the activity about comments, problem statement is quite confusing, as it first says "you should not delete any of it (code)" and then "If you find an illegal for-loop, you should remove the entire loop".  
Maybe this second sentence should be reworded.  

Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/6e554ffe0eb345c4a343a63b4f436db5/67d05789483a44bf8c3b095b974c188a/6?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%40ab309269b55a4a8a9e5a9d7c91fa1bcf

**Comment by chrissmiller** [comment]
Thank you, fixed! Switched wording to state that learners should comment out the entire loop instead of telling them to remove it.
