### ISSUE TITLE
More precision in problem statement (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#433]
For the activity about cost of cement, some learners have difficulty to understand what is the calculation to do.  
One of them suggests that the given example is detailed.  

Link to the activity:  https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccb75017dce84804a4477600cf09014d/4c4f062124eb47f99ab23cf7228a1109/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%40f5b37f8ce0924aa19f3141b6a7323444

**Comment by chrissmiller** [comment]
Added clarification by explaining the example in depth in the problem statement - should be clearer now!
