### ISSUE TITLE
Some typo in course 1

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#436]
Some learner points out a typo under the codecast about correcting common syntax errors regarding variables.  
It is written: If you can't see this Vodecast, please click here.

Link to the Codecast:  https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccf660cc6a1141e0a9bebfc515ce320a/486dacf4bd094519afe1c91af2e17fee/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%40cbacb57afab143ec93b53e6c5a1a8551

**Comment by catherinechoww** [comment]
<img width="460" alt="Screen Shot 2023-05-22 at 1 42 02 PM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/98115742/f52e17ee-b158-493b-84a6-497121a858b5">
Typo seems to have been fixed - closing issue
