### ISSUE TITLE
Taskgrader too indulgent (for a change) (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#438]
Activity about multiple for loops:
Taskgrader accepts codes which don't add a new line between the two loops. 
That seems to be in contradiction with problem statement: 

> Warning: Your output needs to look exactly like the above output.

Link to the activity:  https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/6e554ffe0eb345c4a343a63b4f436db5/398f265fd5d2469f9e2c06afcbd08887/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%406011d813025841d099ed5c98ef654126

**Comment by chrissmiller** [comment]
Fixed, just had to change the diff call
