### ISSUE TITLE
Incorrect hint (course 7)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#439]
On the activity about using the JPEG library, some learner remarked that the hint isn't correct, as the given path for the library is /user/lib/libraryname.so instead of /usr/lib/libraryname.so

Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+2T2018/courseware/f838e66a12864002be52ceaf73f2842f/7c4f5f4801354e60abefdab9d4f870eb/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.07%2B2T2018%2Btype%40discussion%2Bblock%40bc24378fda6340a097227d5b776942bd

**Comment by deladan** [comment]
Error is still there, and some other learner reported it again.

**Comment by catherinechoww** [comment]
Corrected two typos in the hint so that it went from:

You can incude a library by including the path /user/lib/libraryname.so before the name of the program to compile.

to:

You can include a library by including the path /usr/lib/libraryname.so before the name of the program to compile.
