### ISSUE TITLE
we value your feedback

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#44]
Which course: 1 Getting Started What type of content: we value your feedback URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/course/#block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018+type@sequential+block@422a43345a7a412ba45faa9c6db35af0 Description:  we value your feedback   points nothing... other comments:  your name: Cat screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel:

**Comment by Kitkatniss** [comment]
The survey has been added.

Close this ...
