### ISSUE TITLE
Taskgrader accepts code which don't do what is expected (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#444]
In the activity about printing quotation mark, Taskgrader accepts code which doesn't display them, such as:  
`printf("Dennis Ritchie said:\nThe only way to learn a new programming language is by writing programs in it.");`

Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/6e554ffe0eb345c4a343a63b4f436db5/bd02d17e76714247aff2f15a044c6153/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%408c914b2aa6e14fb5ad78a85fa3007330

**Comment by chrissmiller** [comment]
This is a problem caused by the use of the the autocorrect library which demands punctuation-stripped text. I've implemented a pretty hacky fix - could find more elegant way, but I think considering the scope of the issue it's fine if it's specific to this task.
