### ISSUE TITLE
Confusing solution (course 2) ?

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#445]
Some learner finds that the solution of the activity "guess my number" is unclear.  
I don't really agree with her but here's the link to the thread (look for Jennifer2 comments):  
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/discussion/forum/3ee766d2843da0928888c9a1e43c6744933d2032/threads/5c00b6514fc2300a04001708
Link to the activity: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/c994b80204d747b6aa16ad991f4b1904/bcaeeafdf43b417e910a6ac07da4bd83/2?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%402abd715b5cee4064be6142f8920e2481

**Comment by catherinechoww** [comment]
Can't view this user's comment anymore - closing issue because no one else has raised concerns about the solution since this user back in 2019.
