### ISSUE TITLE
Issue with taskgrader (course 2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#449]
Trying to find error in some code from a participant, about the monitoring of a chemical experience, I've pasted it to the wrong activity (university depense).  
But surprise, program was accepted!!  
I tried to submit it again, and then it only passed the first two tests.

Code:  
```
#include<stdio.h>

int main(void){

int min;

int max;
int temp;
scanf("%d %d", &min ,&max);
scanf("%d", &temp);
while(temp != -999){
    if (temp<min || temp>max){
        printf("Alert!\n");
    }else{
        printf("Nothing to report\n");
    }
    scanf("%d",&temp);
}
return 0;

}


Link to the activity: 
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/c994b80204d747b6aa16ad991f4b1904/174acb6ba12746b4aeea29d80c7ec94a/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%409a7344f4f7924472bef290be6246e538
```

**Comment by catherinechoww** [comment]
See below: the above code does not pass the test.
<img width="780" alt="Screen Shot 2023-06-08 at 5 28 21 AM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/98115742/b9599352-82f6-4687-b018-f1558c1870e1">
