### ISSUE TITLE
Some feedback about difficulty in course 1

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#455]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/e4ecbcdf415f7e838d73d0726e2ba90980d66ba0/threads/5c3a2aa63eb9e609d0000bec

**Comment by deladan** [comment]
Seems someone (the author?) deleted the thread.

**Comment by catherinechoww** [comment]
Seeing that user deleted their feedback and it's no longer viewable - closing issue.
