### ISSUE TITLE
question on the exercice about trees

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#47]
Which course: 2 Language Foundations What type of content: question on the exercice about trees URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/a86febae1149479d971ae6edbd850c51/536186d847234e318b5de5d39b18b1b4/?child=first Description: This summer that code worked It doesn't work with only  if this   if that   if thisthat  else...  This time  I had to write many  else if  like :   if(Tinuviuel){printf( Tinuviel ) }     else if(Calaelen){printf( Calaelen ) }     else if(Falarion){printf( Falarion ) }     else if(Dorthonion){printf( Dorthonion ) }     else {         printf( Uncertain )      }  Is this intented ? other comments:  your name: Kitkatniss-Cat screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel:

**Comment by Kitkatniss** [comment]
The code below was accepted. But I had to put "else if" but in this summer's course, it was only "if" needed

#include <stdio.h>
int main() {
    int taille =0;
    int nbfolioles =0;
    scanf("%d", &taille);
    scanf("%d", &nbfolioles);
    int Tinuviuel = taille<=5 && nbfolioles>=8;
    int Calaelen = taille>=10 && nbfolioles>=10;
    int Falarion = taille<=8 && nbfolioles<=5;
    int Dorthonion = taille>=12 && nbfolioles<=7;
    if(Tinuviuel){printf("Tinuviel");}
    else if(Calaelen){printf("Calaelen");}
    else if(Falarion){printf("Falarion");}
    else if(Dorthonion){printf("Dorthonion");}
    else {
        printf("Uncertain");
    }
return 0;
}

**Comment by chrissmiller** [comment]
I think this was just a suggested solution change from the previous course, but (unless I am mistaken) I believe just using if statements would work fine here! But yeah this is the expected/correct solution and you are supposed to use else if.
