### ISSUE TITLE
Issue with pre-course survey (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#471]
Some learner reported that Taiwan doesn't appear in list of countries in answer to question: In which country do you reside?  

Link to survey:  https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/7f15846e372741c483ee67f37d93f346/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40vertical%2Bblock%40e5072176279143ca9ce36a76d75776ac

**Comment by deladan** [comment]
Other learner says that Korea isn't present neither.
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/d38a7954e9b9aaa7d9c256ca7c9c01cfa6cb4ed9/threads/5c5eb5443eb9e6099d00225f

**Comment by mgoudz** [comment]
"Taiwan (ROC)" has been added to the choices. Korea appears in the list as "Democratic People's Republic of Korea" (north) and "Republic of Korea" (south)

**Comment by mgoudz** [comment]
Taiwan has also been added to the pre course surveys for courses 2-7.
