### ISSUE TITLE
Incoherency with absolute path in some video (course 7)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#482]
Some learner pointed out that the absolute path written by Petra in [this lecture](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+2T2018/courseware/99f41a3930e044be961acaeace469305/cb1e428a95cf44e09a4de74412af3c6c/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.07%2B2T2018%2Btype%40discussion%2Bblock%4022c805a883c94197ac5701cbaccfb4b0) at 9'28 isn't correct and should be /home/user/weather.h rather than /usr/hom/weather.h.  
I can't remember if that has already been reported.

**Comment by petraBT** [comment]
Same issue at 10:56.

**Comment by EllaHa** [comment]
It has been modified and uploaded on Studio
