### ISSUE TITLE
Typo in some Taskgrader activity in course 5

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#484]
In the [activity about manipulating structures with functions](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/courseware/58099ea386614233830b63363dc6db01/d25d4867ce6a4cd1929358ee146903cc/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B2T2018%2Btype%40discussion%2Bblock%40c7240c419b074fc09c8f2c1d6c8db69a), there is a typo in comment in provided code.  
Indeed, in this comment, we're asked to define here advanceDate function, whereas in main function, that we can't modify, it's advanceDay function which is used.

**Comment by catherinechoww** [comment]
Issue similar to:
[https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/696](url)

All typos corrected
