### ISSUE TITLE
ill-advising warning from Taskgrader

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#486]
In course 1,[ activity about finding the remainder in integer division](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccb75017dce84804a4477600cf09014d/1aef4d47f747417aa9c43a8f083c9072/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%40a0fa46f9329f43868596be29f5943ee9)
Some learner got this warning about Taskgrader:  
```
Suspicious scan statements below
example of expected syntax: scanf("%d\n", &example);

line   4 :  scanf("%d\n%d", &totalMatches, &boxSize);
```
I advised him not to pay too much attention to this, but I'm a little puzzled that expected syntax would be: `scanf("%d\n", &example);`
Why this \n at the end of the string, which raises issue for several learners when they tried to run their code on sandbox?

**Comment by chrissmiller** [comment]
Fixed, thanks!
