### ISSUE TITLE
Some typo in course 5

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#491]
In activity about [allocating memory for structures](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/courseware/8e24632b4bc34ba2a927367da7e0c22b/b99d6e074c9e4d1f96981b78d8d13231/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B2T2018%2Btype%40discussion%2Bblock%40d617f3358b484d43b76167cfa825d06f), learner remarked some typo in problem statement:  

> initializePoly() should receive as input a pointer to the first structure in an array of structures as well as "in" integer, indicating how many points can be stored in the array.
> 
> the double-quoted word 'in' should be 'an' I think.

**Comment by catherinechoww** [comment]
See attached screenshot: Fixed typo in problem statement.
<img width="786" alt="Screen Shot 2023-06-14 at 9 26 08 AM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/98115742/02681ae1-1376-4f86-9725-26808f15bcdd">
