### ISSUE TITLE
Typo in quiz course 6

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#502]
[Quiz about interactive programs](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/632a112f8d4e46c88cf195f34e486a4f/7c1d9bb1804444f092456eeeecb8cffd/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40discussion%2Bblock%4064bda04351f749b8b15051f67feefd29)

Second question should be reworded as: "How do you use the file otherans as **an input** to a program executed by ./prog ?"

Reported by some learner in the forum

**Comment by catherinechoww** [comment]
See attached screenshot: fixed typo in question 2.
<img width="856" alt="Screen Shot 2023-06-14 at 9 20 52 AM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/98115742/38cc81a2-1b13-490e-9458-62d2c7b49ee2">
