### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rserranosmith** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#510]
There is a typo in course 3: **Unit 3.2: > Determining the amount of memory used for different data types > Be aware of the largest possible value for an integer!**

[https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/5c40ed165b45423496c1c8c8fdca08d9/91f8edcd857f410b82baa1860866f4ae/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2018%2Btype%40vertical%2Bblock%408048e21619614947871d6cd87cac5e33](url)

The header sentence for the activity says **"What is the largest integer that you could store in the system? Start listening this Codecast to get the answer!"** and there needs to be a **to** in between **listening** and **this**.

**Comment by catherinechoww** [comment]
See attached screenshot: fixed typo and closed issue.
<img width="945" alt="Screen Shot 2023-06-14 at 9 14 30 AM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/98115742/55265266-eae2-46ed-8b5c-169d926169d6">
