### ISSUE TITLE
tests to review in activity about dividing numbers (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#511]
In the [activity about dividing numbers](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccb75017dce84804a4477600cf09014d/54f5feb1eb3749e9812eaf4278ce3d9c/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%40aec5050c7eaf4839897327a0bd9ee579), a program that will only read an integer and not a decimal value is still accepted. 
I wonder whether tests should be modified in order to add decimal inputs too.

**Comment by petraBT** [comment]
Okay: I added a test that only works if the correct datatype is used. I also added a second example to the problem statement to reinforce this requirement.
