### ISSUE TITLE
little inconsistency in correction in course 1

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#513]
In [activity about printing the x8 multiplication table](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/ccf660cc6a1141e0a9bebfc515ce320a/45513fa0b0c54101aee6dd481ef09257/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%404dde839d3b64436c812f456c5f5b98f2), solution code is using index i from for loop.  
It seems to me that in this course, we're taught to use an extra variable instead.   
Some learner asks about this in forum.
Shouldn't it be the same in the correction?

**Comment by petraBT** [comment]
Fixed - replaced solution with more appropriate one.
