### ISSUE TITLE
'incorrect' for syntax in activity in course 1

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#520]

**Comment by deladan** [comment]
In the [activity about commenting instructions](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/c994b80204d747b6aa16ad991f4b1904/7274ebb9203b4dc5ac1dd1581089f3be/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%40f656c6f89b2f439288dfe3aba7ba2701), there is a for loop where variable is declared inside the for loop.
This actually is the for loop we have to comment, but this isn't the reason why we do this, so I guess it may confuse some learners.

**Comment by petraBT** [comment]
Good catch! Fixed.
