### ISSUE TITLE
Unfair question (course 4)?

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#521]
Regarding the [quiz about pointer arithmetic](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2018/courseware/27b25e631c254ed09e1f67d84f02a01c/2f01c383f1174864ae2643ecc675db50/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.04%2B1T2018%2Btype%40discussion%2Bblock%405e96e8f56b8c4de0a6138ad33d940f24), question 3, some learner complains that he/she answered according to results in Codecast. He suggests question were mentioning it refers to general case.
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2018/discussion/forum/484baa220e75b90c7e58caa8cce5dbf37d2ed420/threads/5d231ab6d8eab10958003c9e

**Comment by deladan** [comment]
Another learner complaining about this: 
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2018/discussion/forum/484baa220e75b90c7e58caa8cce5dbf37d2ed420/threads/5d365e1c387a590767000919

**Comment by petraBT** [comment]
Thanks! I added a note to the quiz.
