### ISSUE TITLE
misleading hint (course 3)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#525]
In [activity about finding the smallest integer](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/9afb1233a3d74a62acc1625236e57a96/07d4663586b74bd6abd7b94bf3326474/6?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2018%2Btype%40discussion%2Bblock%409e7dd39b807b452b8570729368aea7fd), solution doesn't follow the given hint.  
Shouldn't this one be modified?

**Comment by deladan** [comment]
Another student reported this incoherence.  
[link to the thread](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2020/discussion/forum/66f06ed76db81c88fc1540082342e32f0fe9ebc1/threads/622e744f3978a804714209b5)

**Comment by catherinechoww** [comment]
<img width="1113" alt="Screen Shot 2023-08-04 at 9 51 43 AM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/98115742/3a199c99-4371-4b73-b4ce-fd2799e649a7">

Fixed hint to match solution.
