### ISSUE TITLE
typo in problem statement (course 7)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#545]
In [activity about using math library](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+2T2018/courseware/f838e66a12864002be52ceaf73f2842f/20c36bf48d224858a37200c5de92cf3f/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.07%2B2T2018%2Btype%40discussion%2Bblock%4040dba905e0bd4d18b6af25c711ae4196), in last sentence, "Your program's source code si stored in program.c" should be "Your program's source code **is** stored in program.c"

Reported by some learner in forum

**Comment by catherinechoww** [comment]
See attached screenshot: typo has been fixed.
<img width="825" alt="Screen Shot 2023-06-14 at 9 07 43 AM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/98115742/1398619c-b834-469e-8602-87ec99952943">
