### ISSUE TITLE
Test should be modified in activity about reading numbers from file (course 7)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#552]
In [activity about reading numbers from file](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+2T2018/courseware/b2fc63d70fe74a38963d1ddf871946b4/c69c696065964550835dcade17e8e61a/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.07%2B2T2018%2Btype%40discussion%2Bblock%4096ebca3fd3bf4db08145d6ce13b2adab), there is one single test.  
I suspect that it provides numbers whose average is an integer number, as we can submit some code which doesn't cast sum to double before computing the average.  

Indeed, this code is successfully submitted:   

```
#include <stdio.h>

int main(void) {
	FILE *ifile;  
	int i, N, grade, sum;
	double average;
	
	sum = 0;
	
	ifile = fopen("studentGrades.txt", "r"); 
	
	fscanf(ifile, "%d", &N); 
	
	for (i = 0; i<N; i++) {
		fscanf(ifile, "%d", &grade);
		sum += grade;
	}
	
	fclose(ifile); 
	average = sum / N;
	printf("%.2lf\n", average);
	
	return 0;
}

```
whereas I think it gives incorrect results if average isn't an integer number.

**Comment by remisharrock** [comment]
Thanks Isabelle  @deladan and Ricardo @rserranosmith for reporting this ! we will improve the tests by training two new students joining the team ! @rserranosmith I will introduce them to you !

**Comment by catherinechoww** [comment]
Because the purpose of this program is supposed to read the contents of a specific file "studentGrades.txt", there is only one possible answer. Therefore, there can only be one test item for this problem - closing issue.
