### ISSUE TITLE
Lack of consistency in some hint (course 2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#555]
[Activity about array computation, price per ingredient](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/c994b80204d747b6aa16ad991f4b1904/7274ebb9203b4dc5ac1dd1581089f3be/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%40f656c6f89b2f439288dfe3aba7ba2701), first hint says:  

> Make sure to declare your array as size 10, and make sure that users cannot enter a number of ingredients greater than 10.

However, provided solution doesn't check this, and crashed if run if user types a greater than 10 number.

As Taskgrader only provides valid data when testing the code for this problem, is this hint really relevant?

Issue raised by a learner in the forum, link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/discussion/forum/32d99a2664213f233fd472447e5c142d5d2a0f09/threads/5d9f9aac8149fd096800374a

**Comment by catherinechoww** [comment]
New hint:

Remember to declare the array with a size of 10, then read the quantities into the array. Once the quantities are stored in the array, accessing the correct quantity is as easy as using array[idNumber].
