### ISSUE TITLE
some \n in scanf in solution (course 2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#556]
I'm not sure it wasn't reported before, but in provided solution of [activity about array computation, price per ingredient](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/c994b80204d747b6aa16ad991f4b1904/7274ebb9203b4dc5ac1dd1581089f3be/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%40f656c6f89b2f439288dfe3aba7ba2701), there is a scanf instruction where is written a \n character.  

Shouldn't this be avoided?

**Comment by catherinechoww** [comment]
scanf() in provided solution no longer contains '\n'
<img width="1157" alt="Screen Shot 2023-06-14 at 9 05 23 AM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/98115742/d5cfae6b-4108-4c29-96ac-613455aefedd">
