### ISSUE TITLE
Quiz about C developers (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#565]
Some learners disagree with expected answer to last question in quiz about vocabulary (https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/33129229b7ae4999b57f03be444c2dd0/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2018%2Btype%40discussion%2Bblock%40bb214b4ed3e84f689a1914fbc7a6bb61).
Here link to thread (look at ifiwasakid comment): https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/discussion/forum/a99d3f2a73bcbcb51394dcb4376fe2dabf767589/threads/5d11ace5507a7a09b7003289

**Comment by catherinechoww** [comment]
Unable to see user's complaint about correct quiz answers, but the answers are correct.

Coursera version of the quiz:
[https://telecom-paris.france-ioi.org/en/a/1272350288227256715;p=4702,458602124916982205,4769434107088212490,8123435593727593341,933119068612598309;pa=0](url)
