### ISSUE TITLE
Incorrect code is accepted (course 3)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#566]
In [activity about finding the smallest integer from a list](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/9afb1233a3d74a62acc1625236e57a96/07d4663586b74bd6abd7b94bf3326474/6?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2018%2Btype%40discussion%2Bblock%409e7dd39b807b452b8570729368aea7fd), Taskgrader accepts a code which doesn't initialize some variable and which may give incorrect result if the initial random value were lower than smallest number: 
```
#include <stdio.h>
int min(int, int);

int main(void) {
    
int value1 = 0;
    int value2 = 0;
    int lower;
    int value=0;
    int n;
  
  scanf("%d", &n);
   
 int i=0;
 
   scanf("%d", &value1);
    scanf("%d", &value2);
  
  if(value1<value2){
        value1=value;
 
   }else{
        value2=value;
    }

    for(i=2; i<n; i++){
    scanf("%d", &value);
    lower=min(lower, value);
}
printf("%d", lower);

return 0;
}

int min(int value, int nxtvalue){

    if(value>nxtvalue){
        return nxtvalue;
    }else{
    return value;
}
} 
```

**Comment by catherinechoww** [comment]
<img width="781" alt="Screen Shot 2023-08-04 at 9 30 56 AM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/98115742/ab9558ed-ea20-49cb-9915-b59eabba9b1f">

Bug resolved and code is now marked incorrect for not initializing 'lower'.
