### ISSUE TITLE
Incorrect wording in "a question on this activity" tab

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#568]
From some learner in forum:   

> The first question asked is written incorrectly. When forming a question in English a verb is formally used, therefore the question should be written as such, "Do you have a question on this activity?" I took note to bring recognition to this because as in computer programming correct use of a language's grammar and structure is vital to preserving the system's integrity as well as its level of clarity for proper delivery of expression.

**Comment by catherinechoww** [comment]
Fixed all pages of every course to look like the following:
<img width="989" alt="Screen Shot 2023-05-05 at 9 14 25 AM" src="https://user-images.githubusercontent.com/98115742/236549760-33f814f3-3cc4-4275-b6dd-7d82d689a417.png">
