### ISSUE TITLE
Serious Taskeditor error (possible from Github directory issues)

### ISSUE THREAD

**Issue by Eli-Boardman** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#573]
We attempted to convert spaces in folder names to underscores in Github, and this error ensued when trying to open any task in Taskgrader within the directory where the path was changed.

![taskeditor_error](https://user-images.githubusercontent.com/56078245/69097268-373bfc80-0a24-11ea-9a27-279d8aecaa10.jpg)

**Comment by mblockelet** [comment]
Answered there : https://github.com/France-ioi/task-editor/issues/14#issuecomment-555267582

**Comment by remisharrock** [comment]
is the issue still here ? someone can test ?

**Comment by Eli-Boardman** [comment]
> 
> 
> is the issue still here ? someone can test ?

This was resolved. I believe we now know that the problem involved pushing to Github while being signed into Taskeditor. Michel has since repaired the directory.
