### ISSUE TITLE
Rewording of a question in course 6

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#582]
In [quiz about cat less more](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+2T2018/courseware/953455675ecb40e491f6645e3711295f/a7169c56bd0d42a5a61f14e521b195ad/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B2T2018%2Btype%40discussion%2Bblock%408269fd6ee011487fb31fb6be6dcf4781), some learner was confused by the second question, where he thought that we were expected to write the output of some hello program, or the content of some hello folder, to a file.
He suggests word text is added to the sentence to make it clearer, something like: 
How do you use cat to create a file f with contains the text hello?

**Comment by remisharrock** [comment]
all right, we will fix that in v2.

**Comment by Eli-Boardman** [comment]
Changed to suggested wording above.
