### ISSUE TITLE
Typo on course 5

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#586]
First choice in quiz in Reveal solution for [previous activity "append a node with student data"](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/courseware/ec78e06b33f444cb8265d8c58227da98/ec93d3937a4c4d5499eca2e2785b32c5/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B2T2018%2Btype%40discussion%2Bblock%40ad45db5c1798483a8d71c996fdb3a17a), there is a "chooseing" which should be changed in "choosing".

**Comment by remisharrock** [comment]
thanks, corrected !
