### ISSUE TITLE
MOOC2 Final project: hints and solution

### ISSUE THREAD

**Issue by petraBT** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#590]
The solution of the final project in MOOC2 has an unused variable ("swap"). Also, the indenting could be fixed. Also, please fix the hint - either disable or include a hint.
![Screen Shot 2020-02-06 at 11 44 53 AM](https://user-images.githubusercontent.com/33522257/73958776-6ef56a80-48d6-11ea-8b4b-616d57439475.png)

**Comment by Eli-Boardman** [comment]
Fixed.
