### ISSUE TITLE
MOOC 4 Final project: hints, title, temperature 

### ISSUE THREAD

**Issue by petraBT** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#592]
Hint: same issue as MOOCs 1-3.
Title: Change to "Tracking a Fire Using Arrays"
Also, I don't think 90 degrees is the right threshold to assume there is a fire. The coolest fire burns at around 1000 degrees Fahrenheit. Please change - sorry. This will affect the problem statement, input, checker, solution, etc. Unless you have another idea on how to address this.

**Comment by Eli-Boardman** [comment]
Done. Current settings: a "fire" is any temperature >1000 F, and a "watch zone" is any temperature between 100 and 1000 F (inclusive of end points).
