### ISSUE TITLE
another typo

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#594]
Course 2, [activity about tug of war](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/a86febae1149479d971ae6edbd850c51/dd6988baae994fff80bd8bd9c1884cf4/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%40ea1d9b78328042169dfef7e52f25434f) :
 _calculate a total weight for each time_ should be  _calculate a total weight for each team_

**Comment by catherinechoww** [comment]
Great catch! Edited problem statement to get rid of typo and look as such:
<img width="807" alt="Screen Shot 2023-05-21 at 4 52 31 PM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/98115742/24d10f09-dfbe-4a47-a0a2-6957b3958a48">
