### ISSUE TITLE
mooc 6 unit 3.2 quizz cat less more

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#595]
I can see weird characters in this quizz:

![image](https://user-images.githubusercontent.com/8048877/74652047-7db90880-5185-11ea-91d2-b0eda78a49c0.png)

**Comment by Eli-Boardman** [comment]
Fixed this. It appears to have been an oversight in copying from the original quiz code into taskeditor.
