### ISSUE TITLE
missing quizz in 7.2 compiling

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#598]
following this 
https://github.com/remisharrock/cspace/blob/master/07%20C%20Programming%20Using%20Linux%20Tools%20and%20Libraries/Unit%207.2%20Modularization%20Libraries%20and%20Makefiles/01%20Modularizing%20a%20program/02_qcompiling.txt 
could you create a taskgrader quizz ?
maybe using numbers to do the "matching" ? Or do you have another idea ?
Thanks !

**Comment by Eli-Boardman** [comment]
Done. I handled the "matching" by presenting several options for possible arrangements as a multiple-choice question.
