### ISSUE TITLE
missing quiz in 7.2 create library

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#603]
from 
https://github.com/remisharrock/cspace/blob/master/07%20C%20Programming%20Using%20Linux%20Tools%20and%20Libraries/Unit%207.2%20Modularization%20Libraries%20and%20Makefiles/03%20Creating%20a%20static%20Library/02_qcreateLibrary.txt
could you create a quiz ?
Thanks

**Comment by AadhyaKocha** [comment]
Done and ready to be tested.
