### ISSUE TITLE
Quiz: assign, re-assign and update a variable - numerical response vs. string response

### ISSUE THREAD

**Issue by petraBT** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#607]
In MOOC1, Course  Unit 1.2: Integers, variables and user input  Using variables  Quiz: assign, re-assign, and update a variable, all learner responses are numerical. Yet, it says "String response" in the entry fields which could be confusing. Can this be changed?

Also, the styling looks rather terrible - can anything  be done?

**Comment by AadhyaKocha** [comment]
Changed to "Enter Number" and improved styling a little. Let me know if it should be improved further.

**Comment by petraBT** [comment]
Perfect - thank you!
