### ISSUE TITLE
wrong title in welcome video of course 5

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#609]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/discussion/forum/5361e49d51bf46a5cbfce15ef030e9455f149de1/threads/5e545702c76277091a005b2f

**Comment by deladan** [comment]
Same issue in  "What's next? Closing MOOC5" video

**Comment by AadhyaKocha** [comment]
Since this is version 1 I can't see the error anymore on that forum so i'm not sure what the issue is. The title for Mooc5 whats next in V2 looks right to me.

**Comment by catherinechoww** [comment]
Titles for videos are correct for me. Bug must have been fixed after moving away from V1.
