### ISSUE TITLE
V2 : There are no tests for this task. (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#616]
[Activity about adding comment to existing code](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/6e554ffe0eb345c4a343a63b4f436db5/67d05789483a44bf8c3b095b974c188a/6?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40ab309269b55a4a8a9e5a9d7c91fa1bcf), 
when one submits her code, grader answers there are no tests for this task.

**Comment by catherinechoww** [comment]
Can't find this user's discussion post about the error. Tried to recreate it myself, but wasn't able to. Because of this and the fact that I have never seen another user say so, closing the issue.
