### ISSUE TITLE
Issue with quiz about variables in course 1 V2

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#618]
In [quiz about declaring and naming a variable](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccf660cc6a1141e0a9bebfc515ce320a/486dacf4bd094519afe1c91af2e17fee/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40cbacb57afab143ec93b53e6c5a1a8551), 
first question asks us about incorrect declaration.
But quiz expects the first proposition not to be selected: `int 3littlePigs;`. 

In third question, are you sure about what you wanted to check here?
I've thought that you would wanted to assure that the learner has seen that C is case-sensitive, so that `int Balance ;` and `int balance ;` will create two independent variables.
Correct answer is two compilations errors because of missing semi-colon here, but I find the question deceptive.

Some learner reported issue with first question.
Maybe his/her answer should be reinitialized?
Link to the thread: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/517e9b8f3b9731adf777bfbf13276713572ea886/threads/5e5fc156aab18f07a90000b5

**Comment by deladan** [comment]
Another remark about this quiz.
In last question, if purpose was really to check that learner could spot the syntax errors which are due to missing semi-colon, I understand why so many found the question unclear, as both instructions are displayed on one single line in grader interface, rather than:  
```
If you declare two variables as follows:

int Balance

int balance

then which of the following is true?
```
which seems to be what was expected.
![screen_copy](https://user-images.githubusercontent.com/34571147/99103139-678a8c80-25df-11eb-9e71-88f01a3f5cde.png)



I don't know whether this issue with displaying can be resolved. If not, shouldn't this question be modified as I've suggested earlier?

**Comment by catherinechoww** [comment]
Q1  - 3littlePigs should be selected to obtain the correct answer.

Q3 - put int Balance and int balance in separate lines as proposed, and correct answer is that the variables are independent of each other.
