### ISSUE TITLE
Typo in problem statement in course 1 V2

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#619]
In [activity about dividing decimals with round-off](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccb75017dce84804a4477600cf09014d/4c4f062124eb47f99ab23cf7228a1109/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40f5b37f8ce0924aa19f3141b6a7323444), a learner reported a typo in the explanation of the example.  
In last line, computation should be 45 * 3 and not 45 * 8.

**Comment by AadhyaKocha** [comment]
It should be 45*3 so I have changed it
