### ISSUE TITLE
Issue with quiz in course 6 V2

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#621]
[Quiz about find and locate](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+1T2020/courseware/953455675ecb40e491f6645e3711295f/2cd1aef12a4147dba381e83e10a44580/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B1T2020%2Btype%40discussion%2Bblock%406c9873d6cbe7449aa00b59f89b9f7d63): are you sure about the expected answer to first question?  
The only file whose name has 14 characters in the /usr/bin directory is `df_drivertest2` but it isn't accepted.

**Comment by deladan** [comment]
Some learner found why and reported it: it seems that grader expects an extra space after df_drivertest2.

**Comment by deladan** [comment]
Hello!
After nine months, I observe issue is still there.
Is this space so difficult to remove from the expected answer in grader?

**Comment by AadhyaKocha** [comment]
Works now, thank you @deladan!
