### ISSUE TITLE
No test for activity about costly hotel room in course 2 V1

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#622]
[Activity about more complex if statement](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2018/courseware/a86febae1149479d971ae6edbd850c51/fc9008c149444ca0a623cc332fc01e06/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2018%2Btype%40discussion%2Bblock%40f5755cb0e797445082dce25b9fd57193):
when one submits some code, answer from the grader is that there is no test.

**Comment by remisharrock** [comment]
just tried and it works

**Comment by deladan** [comment]
Indeed, it now works.
