### ISSUE TITLE
Answers incorrectly showing in some quiz in course 5 V2

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#623]
In [quiz about array of structures](miguelfalmeida), some answers of the second question don't correctly show.  
![quiz](https://user-images.githubusercontent.com/34571147/76107480-0551a480-5fd9-11ea-9566-a5dbf0a9a921.png)

**Comment by catherinechoww** [comment]
<img width="470" alt="Screen Shot 2023-08-23 at 9 08 13 AM" src="https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/assets/98115742/57eda6d7-a58d-4697-a437-ba20af85fc6b">

Bug seems to have resolved itself - closing issue.
