### ISSUE TITLE
Typo in answers in some quiz in course 7 V2 (making them incorrect)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#624]
In[ quiz about creating your library](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020/courseware/99f41a3930e044be961acaeace469305/03a438a2ddf7482495f66baf0f141d05/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.07%2B1T2020%2Btype%40discussion%2Bblock%409db4ee568f87452a89504feeee45fa8e), in second question, two commands start with `arc`.
Shouldn't it be `ar`?
Reported in the forum by some learner.

**Comment by AadhyaKocha** [comment]
Just noticed this and I agree that it should be ar. But the answer scripts for V1 say arc which were converted to V2, is it alright if I change both the commands in V2 to be ar or is arc right?

**Comment by AadhyaKocha** [comment]
This is an issue in question 4 of the same quiz as well

**Comment by AadhyaKocha** [comment]
Worked to change it in the answers without messing the view or grades
