### ISSUE TITLE
Final projects scores aren't reported in progress page (V2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#625]
At least in courses 1, 3 and 6.
For instance: 
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2020/discussion/forum/26391989379c6b0f048c52056cb4e8164b1489e3/threads/5e64712b2de842098d3bfedc

**Comment by EllaHa** [comment]
This problem is solved for this user.
