### ISSUE TITLE
linguistic issue in some video on course 2

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#626]
About lecture about nesting for loops, some learner reported that the singular form of dice should be die. 
I thought I've already reported this during the first session but I can't find the issue any more.
Here's the link to the thread: 
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020/discussion/forum/7a6b895a0134bacc179e5e5135c20f448c8ac8ef/threads/5e627f3d35589507fd5de9fc

**Comment by AadhyaKocha** [comment]
This doesn't really matter but should I add a comment below the video? @EllaHa
