### ISSUE TITLE
No hint - course 2 V2

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#627]
In [activity about finding repeated letters](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020/courseware/f2a41407085b4e8c8a5604123388ef33/b32dae4bf4454a179f4cece1403ab0e2/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2020%2Btype%40discussion%2Bblock%4079f7708322cc448ab739c65c846aab34), hint tab is showing and we're told that one hint is available, but there actually is nothing.

**Comment by deladan** [comment]
It's actually the same thing with [final project in course 1](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/dc24f5ecce354be1bbf01983250f9e74/de932eebe17f4085b7676ec8c4632676/2?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%4080afac05b8a74617a1d2cd885e80ff7a). 
Maybe these hint tabs should be removed then.

**Comment by deladan** [comment]
And for [this activity](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2020/courseware/b0efc6858fa44aeeb0b482018e0abf01/4bcb4710a25d44abbb44c558ada6d318/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.04%2B1T2020%2Btype%40discussion%2Bblock%40f620b67434c343e5ad919e1017dea89c) in course 4.

**Comment by AadhyaKocha** [comment]
This was an error we noticed while creating V2 but we cannot change in in taskgrader. It needs to be changed in the back end of taskgrader.

**Comment by deladan** [comment]
Same thing for [activity about arrays and memory in course 4](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2020/courseware/b0efc6858fa44aeeb0b482018e0abf01/622f95d2f08e4f0db6fb9770a31464d0/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.04%2B1T2020%2Btype%40discussion%2Bblock%4070129ecc884b4d05803a44f8d7b1a064).

**Comment by mblockelet** [comment]
Hello, I fixed the issue with empty hints. I normally removed all existing empty hints, but if there's the issue with another task, you just need to reimport the task and it should be fine.

**Comment by remisharrock** [comment]
all right, @AadhyaKocha can you check if you can modify hints now in task editor ? 
thank you @mblockelet !

**Comment by catherinechoww** [comment]
Confirmed that empty hint tabs are gone and that we are able to modify hints in task editor.
