### ISSUE TITLE
Issue with last final project statement course 7 V2

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#628]
[Final project](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020/courseware/bbe0b33365404267b4ca717daab5720b/166aadd2ed1e4a30a5e78c1c455bdc9d/2?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.07%2B1T2020%2Btype%40discussion%2Bblock%407711d209c3ff41a4810e21996b7625d0)
Some learners reported that problem statement isn't correct, supposing supergiant stars radius should be greater than 100 times that of the Sun rather than 1000 times.  
I haven't found the time to test it yet, but it seems that grader agrees with them.

**Comment by AadhyaKocha** [comment]
Online it says it can be 50-1000 suns in reality so not sure what we want the values to be here.

**Comment by AadhyaKocha** [comment]
According to the answer that is allowed, it should definitely be 100 times so I am going changing it to read greater than 100
