### ISSUE TITLE
Issue with some quiz in course 7 V2

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#630]
[Activity about Makefile practice](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020/courseware/99f41a3930e044be961acaeace469305/1ed517a6c28246a5bd9a7b86e28ac371/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.07%2B1T2020%2Btype%40discussion%2Bblock%40c7d6a2a9b3b246febbefca42064b67c9), two learners reported that copying output from Weblinux gave an incorrect quotation mark and made answer not accepted by the grader.  
make: `program' is up to date. instead of make: 'program' is up to date. which is the expected answer.  
Shouldn't the quiz accept both answers therefore?

**Comment by AadhyaKocha** [comment]
I have edited the answer to accept `program' instead of 'program' but am not sure how to accept both answers.

**Comment by remisharrock** [comment]
let me ask Michel on what is the best solution to change the quiz to accept multiple answers without breaking anything.
I will put an issue on the taskeditor/taskgrader repository and make a reference here to get an answer.
Technical info: the task is in the folder :
cspace/07 C Programming Using Linux Tools and Libraries/Unit 7.2 Modularization Libraries and Makefiles/02 Creating and using a Makefile/02_makefile practice

**Comment by mblockelet** [comment]
Hello,

Changing which answers are valid don't break anything in production.

For this type of question, you should change the "Correct answer" to :
* Type : function
* Value of JS function : a function which accepts all the possible answers (returns true if the answer is valid, false otherwise), for instance :

```javascript
function(val) {
  return (val == "make: `program' is up to date." || val == "make: 'program' is up to date.");
}
```

or something better if you're comfortable with regexps for instance.

**Comment by remisharrock** [comment]
Thank you @mblockelet !  @AadhyaKocha could you try that ?

**Comment by AadhyaKocha** [comment]
Thank you! It works.
