### ISSUE TITLE
Error in Codecast about allocating memory in the heap using malloc (course 4 - V1 and 2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#631]
I think I've already reported this but I can't find the issue any more.    
In [this Codecast lecture](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2020/courseware/26662efa0f944539bb7015cfd95bff18/7eebfe6258a9436a8950d8697f6e86f1/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.04%2B1T2020%2Btype%40discussion%2Bblock%40f1e5ddda4b8540e2b56cd5f60cfcef47), near 8:30, Petra says that hexadecimal number 24 stands for 32 + 8.  
It should be 4 instead of 8.    

Maybe that could be rectified in the subtitles, and some erratum may be added below the lecture?

**Comment by AadhyaKocha** [comment]
Agreed. How can I add that as a note for the video?

**Comment by AadhyaKocha** [comment]
Added note above codecast video
