### ISSUE TITLE
some missing activity in course 7 V2

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#632]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020/discussion/forum/fe24a8da1f0bdb6437bdeac210061fda01e160d9/threads/5e71e0a7c1d9cf08a38578e1

**Comment by petraBT** [comment]
Thank you, Isa! Indeed, this activity should not show up in the grading as it is no longer used in this course. My guess is that it failed to get deleted - @EllaHa  and @remisharrock : Should I drag this activity out of c-space and sync, or what is the best way to remove it (it's called 03_create and use makefile and is from V1).

**Comment by petraBT** [comment]
Fixed.
