### ISSUE TITLE
arc command spelling check

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#638]
In Unit 7.2/creating a static library/modify your library (https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020/courseware/99f41a3930e044be961acaeace469305/03a438a2ddf7482495f66baf0f141d05/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.07%2B1T2020%2Btype%40discussion%2Bblock%409db4ee568f87452a89504feeee45fa8e) 
Question 1 should the option be "arc" or "ar" command?

**Comment by remisharrock** [comment]
Should be ar instead of arc, @AadhyaKocha could you change it ? Thanks

**Comment by AadhyaKocha** [comment]
Done
