### ISSUE TITLE
to investigate with france ioi

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#641]
https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020/discussion/forum/f915049c09f8c20c0da07a73954ad459c42d3243/threads/5ed7e1d83b7901084c0b2e2b

**Comment by remisharrock** [comment]
it looks like when there is an infinite loop the error message is not explicit for the learner "Error encountered during solution check. Contact Administrator" ; would we change that to something like "A timeout occured in your program, that might be because of a loop that never stops (infinite loop), check carefully your code and verify that any for loop or while loop in your code has a way to stop". Or something like that ?

**Comment by mblockelet** [comment]
Hello,

It happens because your task is configured with `continueOnError = true` in the `taskSettings.json`. When `continueOnError` is `true`, the checker you wrote for this task is handling the display of such errors (it's the purpose of the option).

```
  "defaultSolutionExecParamsTask": {
    "memoryLimitKb": 16000,
    "stderrTruncateKb": -1,
    "timeLimitMs": 1000,
    "continueOnError": true, <--------
    "stdoutTruncateKb": -1,
    "useCache": true
  }
```

Note that without this option, we do display to the user that a timeout occured.

**Comment by remisharrock** [comment]
Thank you for looking into this, @AadhyaKocha could you look into this ? @mblockelet is it possible to change this parameter in taskeditor without braking everything ? 
Thank you !

**Comment by AadhyaKocha** [comment]
<img width="742" alt="Screenshot 2020-07-30 at 7 40 52 AM" src="https://user-images.githubusercontent.com/51734801/88936681-04473b00-d238-11ea-9be4-ae832a2e4bab.png">
Changing the parameter worked.
