### ISSUE TITLE
Activity Formatting in MOOC 5.2 V2

### ISSUE THREAD

**Issue by rserranosmith** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#643]
In [MOOC 5.2 > Create a structure to store the coordinates of a point > Activity: Array of Structures](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+1T2020/courseware/8e24632b4bc34ba2a927367da7e0c22b/04aeec2986ef40598100f78876966d13/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B1T2020%2Btype%40discussion%2Bblock%4054b82bf946b946c3a50d638899c7d944) there is an issue in question 2 with the formatting of the problem. Instead of -> , we are getting, -&gt;. The issue is that &gt; is the > symbol, but for some reason the activity is not recognizing it as that. Below is a screenshot of the issue.

<img width="968" alt="Screen Shot 2020-07-02 at 10 51 55 AM" src="https://user-images.githubusercontent.com/49991645/86388449-0d051b00-bc52-11ea-9622-77db8f0b6aa7.png">

**Comment by AadhyaKocha** [comment]
Solved
