### ISSUE TITLE
Issue with wiki?

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#648]
Hello!

I can't access to wiki anymore.
I got the following message:

> There has been a 500 error on the edX servers
> Please wait a few seconds and then reload the page.
> 

Course tells learners to look at "how to post code in the forum" tutorial which is in this wiki.
Does someone else have the same issue?
Shouldn't edX asked about it?

Thanks!

**Comment by EllaHa** [comment]
Thanks Isabelle, we all have the same issue. we have open an issue to edX! Thanks for noticing it.
