### ISSUE TITLE
Typo in activity: assign, re-assign, and update a variable (course 1 V2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#650]
Question 4 of [activity about assigning, re-assigning, and updating a variable](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccf660cc6a1141e0a9bebfc515ce320a/05c2e747f2bc429d979fd2c529f5b8a1/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40a0453e1ed42a4c0f9860d38ffcb3b74f): shouldn't "terminate" take an 's' in "Finally, the program terminate with the following instructions:"?

**Comment by AadhyaKocha** [comment]
Fixed!
