### ISSUE TITLE
Typo in codecast course1 V2

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#651]
In [codecast about reading integer input using scanf](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccf660cc6a1141e0a9bebfc515ce320a/a9e59ead57c846759aefb055a2a5c6f2/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40ef41c2d89d844ac4bf9383872d183165), there is a typo in some sentence in the program.
`printf("Whare is your age ?\n")
`
This instruction appears around 00:58.

I don't remember whether this typo has already been reported and I suppose it can't easily be rectified.
For another version of this course?

**Comment by AadhyaKocha** [comment]
It's a pretty small error but would be hard to change I'm guessing. Should I just add an HTML block stating the spelling correction?

**Comment by AadhyaKocha** [comment]
Added a note for this error.
