### ISSUE TITLE
bubble sort - course 2

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#654]
Several learners have suggested bubble sort code, which is introduced in [unit 2.3](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020/courseware/f2a41407085b4e8c8a5604123388ef33/b32dae4bf4454a179f4cece1403ab0e2/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2020%2Btype%40discussion%2Bblock%4079f7708322cc448ab739c65c846aab34), could be improved this way:  

> for (j=0; j<size-1; j++) {
>     for (i=0; i<size-j-1; i++) {

Shouldn't this be added in a remark below the Codecast lecture?

**Comment by AadhyaKocha** [comment]
Correct statement. Made note of this and other optimizations in this [codecast](https://studio.edx.org/container/block-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020+type@vertical+block@cd0cb69fba5d45c2b4dee7631b8ec226).
