### ISSUE TITLE
Some improvement of Taskgrader's interface?

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#655]
When one comes back to some activity, even if one has already successfully completed it, one gets the message:  
"You haven't submitted any answer yet."  
Which is quite confusing, particularly now that scores don't appear directly on the activity, or in the Progress chart.  
Several learners ask about this in the forum.

Isn't it possible to remove this message?

**Comment by mblockelet** [comment]
Hello, I changed the message to "Results of your next submission will appear here." which is more neutral.

**Comment by AadhyaKocha** [comment]
Sounds good!

**Comment by deladan** [comment]
Indeed, but initial message "You haven't submitted any answer yet" is still present when I come back to a solved activity.
