### ISSUE TITLE
Issue with Weblinux on Firefox

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#658]
I just want to report an issue I run into with Weblinux (Ubuntu, Firefox).
Weblinux boots without any issue, but I can't write into it.
I've tried clearing the cache, and I don't use any ad-blockers.

Issue doesn't show with Chrome.

**Comment by remisharrock** [comment]
Tried it with Ubuntu 20.04 LTS and firefox 83.0 (64 bits) and could not reproduce the problem.
What versions are you using exactly ?

**Comment by deladan** [comment]
Hello Remi,

I'm using Ubuntu 18.04 TLS and firefox 83.0 (64 bits).
Issue must be local, I'll try to find out.

**Comment by remisharrock** [comment]
can you try going to https://s-macke.github.io/jor1k/demos/compile.html  and see if you can write some text in the terminal on the left and code on the right ? thanks !

**Comment by deladan** [comment]
Hello Remi,

I can't write in the terminal.
More specifically, I'm able to write some characters (e for instance) but other behave like browser shortcuts.
For instance, typing an a makes me go to previous tab in the browser, typing a b creates a new tab...

**Comment by remisharrock** [comment]
Hi Isabelle, can you try something else then:
create a clean empty new profile on firefox and launch firefox with this new profile and test again. You can go to your old profile afterwards. To do that here are the steps: 
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Multiple_profiles
specifically:

TO CREATE A NEW PROFILE:

Creating a profile through the Firefox browser
You can create a new Firefox profile directly from the browser.

Type about:profiles into the browser URL search bar
On the page, click Create a New Profile button
Read the introduction, and click Next
Enter a profile name for your new Profile. Use a profile name that is descriptive, such as your personal name. This name is not exposed to the Internet.
Optionally, to change where the profile will be stored on your computer, click Choose Folder...
To create the new profile, click Finish.

TO CHANGE TO ANOTHER PROFILE:

From profile manager inside Firefox
If you already have Firefox instance running, you can open another profile from the integrated profile manager on any platform:

Type about:profiles into the browser URL search bar.
Find the profile you want to use.
Press the “Launch profile in new browser” button next to it.

**Comment by deladan** [comment]
Hello Rémi,

Sorry for the late answer.
I tried it and I could write into weblinux with a new profile.
I'll try to find what is causing the issue in my Firefox profile.

**Comment by deladan** [comment]
I found it.
There was a module (sakakey) which was running for some unknown reason.
Deactivating it solved the issue. I'm very sorry for the irrelevant thread.

**Comment by remisharrock** [comment]
it's always good to know the cause of such issue because I'm pretty sure other students may have the same problem. Thank you !
