### ISSUE TITLE
Arrays with variable size

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#662]
In the three first courses of the series, a lot of learners published programs where they have defined an array with a variable size, such as:
```
int ingredients;
scanf("%d", &ingredients);
double price[ingredients];

```
Actually, I think this hasn't been explicitly forbidden in lectures, and grader doesn't make any issue with that. Therefore, learners won't know they are doing illicit thing.  
Shouldn't some warning be added to course 2, when arrays are introduced?

**Comment by AadhyaKocha** [comment]
Note added in [using arrays of integers](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020/courseware/c994b80204d747b6aa16ad991f4b1904/7f90c0855f624fbfa70cedcdc1ba212e/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2020%2Btype%40vertical%2Bblock%40d2b11ca71f55477aa1dc0e2707e5f94d)

**Comment by deladan** [comment]
Hello AadhyaKocha,

That's a good thing, but I suggest you don't tell about malloc there, and only say that dynamically reserve memory will be introduced in some next course.
In all exercises where arrays are mandatory, solution is to give them a fixed size which would be big enough, according to problem statement.
I think you'd rather guide learners to this solution.

**Comment by AadhyaKocha** [comment]
Changed the wording according to this direction.
