### ISSUE TITLE
typo in final project of course 3

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#664]
First sentence of problem statement of [final project in course 3](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2020/courseware/d03b7f5981d34306857cff648e075303/7d05eaf656bb4a87b6b79566a0ab581d/2?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2020%2Btype%40discussion%2Bblock%4008756e12d06e4b6eb5f5d4e75e879119): 

> Write a function isReverse() that checks wether a given word is the reverse of another given word.

Shouldn't it be whether?

**Comment by AadhyaKocha** [comment]
corrected
