### ISSUE TITLE
Enhancement of course 1 about naming variable

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#666]
I've already reported this, but in [quiz about declaring and naming a variable](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccf660cc6a1141e0a9bebfc515ce320a/486dacf4bd094519afe1c91af2e17fee/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40cbacb57afab143ec93b53e6c5a1a8551), first question is a trap, as for should be a valid variable name according to what is said in course in [this codecast lecture](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccf660cc6a1141e0a9bebfc515ce320a/486dacf4bd094519afe1c91af2e17fee/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40cbacb57afab143ec93b53e6c5a1a8551) (do's and don'ts).  
I know that learners may submit as many answers as wanted, and that they could try each instruction in Codecast, but I think there should be an addendum below the video saying that, in addition to the rules which are given in the lecture, there are some keywords which can't be used as variable names.  

Another issue with this quiz (but already reported too) is the last question.
I think question is missing the point, and that the missing semi-colons should be added and expected answer should be "These variables are independent of each other."

Sorry to be redundant, but there are a lot of posts about it in the forum.

**Comment by remisharrock** [comment]
thank you, I'll ask michel for the second question !

**Comment by remisharrock** [comment]
https://github.com/France-ioi/taskgrader/issues/93

**Comment by AadhyaKocha** [comment]
Questions 1 solved by pasting the words in this [link](https://www.ibm.com/support/knowledgecenter/SSCH39_1.0.0/com.ibm.debug.ug.doc/ugdita/rcppres.html). Questions 2 is shown to be solved by Michel in [France-ioi/taskgrader#93](France-ioi/taskgrader#93)
