### ISSUE TITLE
There are no tests for this task

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#669]
Hello,

For a few days, it happens that Taskgrader doesn't want to grade the program, with the message: "There are no tests for this task".
If one tries submitting their code several times, it finally achieves to evaluate it.  
I have run several times into this issue, and several learners too, in different courses.

**Comment by EllaHa** [comment]
report done to France ioi thanks Isabelle!

**Comment by EllaHa** [comment]
This issue was solved.
