### ISSUE TITLE
A typo in course 7

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#671]
Some learner reported a typo in the last sentence of problem statement about [using the math library](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020/courseware/f838e66a12864002be52ceaf73f2842f/20c36bf48d224858a37200c5de92cf3f/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.07%2B1T2020%2Btype%40discussion%2Bblock%4040dba905e0bd4d18b6af25c711ae4196):
Your program's source code **si** stored in program.c,

**Comment by AadhyaKocha** [comment]
corrected.
