### ISSUE TITLE
final project course 2

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#672]
For the [final project of course 2](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020/courseware/7ec2c7ecef5d4d2aa242ae5d7b6cb956/a74c14db6c3140e2883642ea60d13a64/2?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.02%2B1T2020%2Btype%40discussion%2Bblock%40dcdecf38c8364c069cedceb5211dfc7c), 
Shouldn't the maximum number of students, and the maximal length of their names, be given in problem statement?  
Without this information, won't learners tempted to declare arrays with variable size, as they don't know about `malloc` function yet?

**Comment by AadhyaKocha** [comment]
Added statement: "Note that no name has more than 50 characters and there are no more than 30 students."
