### ISSUE TITLE
Issue with quiz in course 1, sometimes giving incorrect feedback

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#679]
[Quiz about declaring and naming variables](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccf660cc6a1141e0a9bebfc515ce320a/486dacf4bd094519afe1c91af2e17fee/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40cbacb57afab143ec93b53e6c5a1a8551)

[https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/517e9b8f3b9731adf777bfbf13276713572ea886/threads/6019c1459c2aee0989ddc14c](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/517e9b8f3b9731adf777bfbf13276713572ea886/threads/6019c1459c2aee0989ddc14c)

I couldn't reproduce the issue.

**Comment by AadhyaKocha** [comment]
Haven't been able to reproduce it either. The answer is also right on Task grader and only correctly specified as option 'd'.
