### ISSUE TITLE
No reported score for final project courses 2 and 5

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#680]
Some learner reported an issue with the final project score, which doesn't show in her edX progress, for both courses 2 and 5.
[https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+1T2020/discussion/forum/2b73715ce897e1a83a6571f42775f975a489fa3a/threads/6019dafcf012b7084364acb0](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+1T2020/discussion/forum/2b73715ce897e1a83a6571f42775f975a489fa3a/threads/6019dafcf012b7084364acb0)

**Comment by deladan** [comment]
Another learner, for the final project of course 1:
[https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/course/threads/601a6480cfe4fd07de252749](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/course/threads/601a6480cfe4fd07de252749)

**Comment by deladan** [comment]
Hello @EllaHa ,
I've read your answer but I have understood final project score was automatically added to edX progress, unlike other exercises.  
For instance, in course 6, I haven't reported my scores to edX yet, however, final score is showing:  
![Capture d’écran de 2021-02-04 21-37-04](https://user-images.githubusercontent.com/34571147/106952413-62962e80-6731-11eb-99b7-cc5df8b96ff5.png)

**Comment by EllaHa** [comment]
Hi Isabelle, 

thanks for raising this issue. The grading problem with Antonia has been solved for the second learner, there is still a problem left, we are working on it. Thanks for reporting it; 


Best,

**Comment by deladan** [comment]
Hello, 
Same learner is experiencing the same issue with course 6's final project.
[https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+1T2020/discussion/forum/3837e3c1a396a2321f43344347c07d6571148c38/threads/603e1b42192fdb0484f7f952](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+1T2020/discussion/forum/3837e3c1a396a2321f43344347c07d6571148c38/threads/603e1b42192fdb0484f7f952)

**Comment by deladan** [comment]
Hello,

There is another learner who experiences same issue with final project's grade which doesn't show, in course 1.  
Link to the thread: [https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/57ead07b1a3cb8a62455f43cb57836e1c355e7d0/threads/604a0e16e136290477b1583c](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/57ead07b1a3cb8a62455f43cb57836e1c355e7d0/threads/604a0e16e136290477b1583c)

**Comment by EllaHa** [comment]
Thanks Isabelle for reaching out, the problem is now solved. 
Best,

**Comment by deladan** [comment]
Hello @EllaHa ,

Another learner is running into the same issue in course 4:  
[https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2020/discussion/forum/1b03e9f9079f18633641bfdab397d6f4b1d2233d/threads/606a3bbde136290450b1a11a](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2020/discussion/forum/1b03e9f9079f18633641bfdab397d6f4b1d2233d/threads/606a3bbde136290450b1a11a)
