### ISSUE TITLE
Suggestion of enhancement of problem statements

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#681]
No big deal, but a lot of learners were confused in course 1 because they first thought their program should deal with all examples in one execution.   
I wonder whether problem statement might be clearer about that.  
Rather than spelling Examples (I agree that plural should be enough to understand that there are several examples, but as I've said, there is a great number of messages in the forum about misunderstanding this), maybe it should be written Example 1, Example 2, ...

**Comment by AadhyaKocha** [comment]
I'm confused. Can you please provide an example of a quiz that uses this wording?

**Comment by deladan** [comment]
Hello AadhyaKocha,

It isn't about quizzes, but about coding problems
For instance, for the [problem about printing the multiplication table of an input number](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccf660cc6a1141e0a9bebfc515ce320a/a9e59ead57c846759aefb055a2a5c6f2/?child=first), in course 1, several learners wrote a code which prints the multiplication table of 8 and the multiplication table of 5, or a code which tries to read two numbers from input in order to print two multiplication tables.

**Comment by AadhyaKocha** [comment]
That was helpful, thank you. I have added more specification for the example numbers and transparency on how we test their code with different inputs.

**Comment by deladan** [comment]
I'm sorry to re-open this issue but there are still learners who don't understand examples are distinct program's executions on other coding problems.
Couldn't my previous suggestion be applied to all?
