### ISSUE TITLE
Naming a variable: do's and don'ts

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#683]
In[ this lecture](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/courseware/ccf660cc6a1141e0a9bebfc515ce320a/486dacf4bd094519afe1c91af2e17fee/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.01%2B1T2020%2Btype%40discussion%2Bblock%40cbacb57afab143ec93b53e6c5a1a8551), it is said that a variable's name has to start with a letter.  
It isn't true as it may begin with an underscore, and learners are asked about that in following course.  
I've seen that some note has been added regarding keywords (which are also missing in the lecture).  
Shouldn't be another precision added about this underscore ?

**Comment by deladan** [comment]
Hello,

Question is posted again about this in the forum.
Couldn't some erratum be written besides the video, about the fact that a variable's name can start with an underscore, and not only with a letter as said in the lecture?

**Comment by AadhyaKocha** [comment]
Added a note under the video
