### ISSUE TITLE
Solution for final project course 7 not accepted by the grader

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#687]
The provided solution for this final problem isn't accepted by Taskgrader, because it doesn't find provided code where it expects to.  
It looks like it's because the initial comments, // Do not modify the main() function! and // Do not modify the printStars() function! were removed.

**Comment by rserranosmith** [comment]
To solve this, we could paste the supplied code that the learner is not supposed to modify, at the end of the problem statement in a code block so that if they accidentally modify the code, they have a method to revert back to the initial code

**Comment by deladan** [comment]
And what about modifying the provided solution, so that it is accepted by the grader? 
Solution is to add the two comments.

**Comment by AadhyaKocha** [comment]
I have added the code as Ricardo mentioned to the question. @remisharrock should we ask Michele to look into the grading to automatically add the comments? Or should I also just make note to not delete comments either?
