### ISSUE TITLE
wrong subtitles (course 4)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#688]
The [welcome video of course 4](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2020/courseware/cb1004a450cf47c1a9f1992ab3772d8f/bed2976f59604bc1ae11e7aff468021d/?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.04%2B1T2020%2Btype%40sequential%2Bblock%40bed2976f59604bc1ae11e7aff468021d) doesn't display correct subtitles.
If needed, I've got a file with the subtitles for this video.

**Comment by AadhyaKocha** [comment]
Fixed https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/715
