### ISSUE TITLE
Codecast  general impression

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#69]
Which course: 4 Pointers and Memory Management What type of content: Codecast  general impression URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2018/courseware/27b25e631c254ed09e1f67d84f02a01c/378f571dbc5d43bfb205e1da1e99287c/?child=first Description: In the first codecast  some important tools & concepts used in this module are not introduced before being used. For example  the  memory  of a computer or the  addresses  of values are used without any introduction. I can guess the 3rd course   Modular Programming and Memory Management   that I didn't finish yet  is actually tackling this problem and introducing properly those concepts so it's ok but maybe you could add a short text or video to warn the students about the  dependency  or maybe point at a video from the 3rd course ? Otherwise  everything still looks great! This MOOC is really one of its kind ! other comments:  your name: Godefroy screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system: Apple's macOS (formerly OS X) which web browser? chrome Status actuel:

**Comment by EllaHa** [comment]
@remisharrock @petraBT any idea how to improve this?

**Comment by petraBT** [comment]
I cannot understand this concern. Maybe the student accidentally skipped "Defining and Dereferencing Pointers" (the previous section of this MOOC)? @remisharrock any ideas?
