### ISSUE TITLE
Not enough tests, and enhancing of problem statement (course 7)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#692]
[Problem about finding the end of a file](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020/courseware/b2fc63d70fe74a38963d1ddf871946b4/1270212dc8a846b89a71657856e5dda1/3?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.07%2B1T2020%2Btype%40discussion%2Bblock%40adb5b46d160b44269620fa75a5b3fb37)

I've already reported this "issue".  
A lot of learners are looking for the greatest average while we're asked to look for the first class which has a greater average than ours. And their programs were accepted by Taskgrader.

I suggest you modify the example in problem statement to: 
95.23 94.80 91.56 96.40 96.55
so the class we need to return isn't the class with highest average. 
And I also suggest test in Taskgrader is modified as well.

**Comment by AadhyaKocha** [comment]
The 2nd example in the quiz already makes this distinction. But as you recommended, I have added a test case in the quiz. Thank you!
