### ISSUE TITLE
Issue with skills checklist in Unit 3.1

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#693]
[Skills checklist](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2020/courseware/9afb1233a3d74a62acc1625236e57a96/b485323cfeeb426e8a2115c8da28033f/?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2020%2Btype%40sequential%2Bblock%40b485323cfeeb426e8a2115c8da28033f)

The last entry isn't correctly formatted:  
![Capture d’écran de 2021-04-27 06-18-10](https://user-images.githubusercontent.com/34571147/116184664-7e054a00-a720-11eb-81bd-7f1021bd640e.png)

**Comment by AadhyaKocha** [comment]
Made the last point an option as well.
