### ISSUE TITLE
typo in some quiz in course 4

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#694]
Hello,

In [quiz about using pointers](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2020/courseware/27b25e631c254ed09e1f67d84f02a01c/d26e90ec3b1f4663aa44006d6b1546fa/5?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.04%2B1T2020%2Btype%40discussion%2Bblock%403daf7c1d16624063880f896601694e78), there is a missing 'r' in the answer 'compiler erro**r**' in second question.

**Comment by AadhyaKocha** [comment]
Fixed!
