### ISSUE TITLE
typo in course 5 presentation

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#695]
In the [home page of course 5](https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.05+1T2020/home), if you display all the presentation of the course, clicking on show more button, the last line is missing a k in "lin**k**ed list":
![Capture d’écran de 2021-04-29 06-07-34](https://user-images.githubusercontent.com/34571147/116501601-7e811a80-a8b1-11eb-8d73-5fe4f42abda0.png)

**Comment by AadhyaKocha** [comment]
Fixed!
