### ISSUE TITLE
Inconsistency between problem statement and provided code (course 5)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#696]
In [activity about manipulating structures with functions](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+1T2020/courseware/58099ea386614233830b63363dc6db01/d25d4867ce6a4cd1929358ee146903cc/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B1T2020%2Btype%40discussion%2Bblock%40c7240c419b074fc09c8f2c1d6c8db69a), there is a contradiction between the problem statement, which asks us to define an `advanceDate` function, and the provided code which uses an `advanceDay` function.

**Comment by deladan** [comment]
A learner just posted a message about this typo too.
Shouldn't this be easily fixed? Solution would be to modify problem statement so it matches with the provided code.
There will be nothing to change within Taskgrader.

**Comment by catherinechoww** [comment]
Yes, wonderful catch. Originally, it said:
<img width="913" alt="Screen Shot 2023-04-27 at 12 33 16 PM" src="https://user-images.githubusercontent.com/98115742/235005331-59887e9c-2a0b-450d-9898-87ef87aecd4d.png">

I have modified the problem statement to now say the following, which matches the provided code for this problem:
<img width="797" alt="Screen Shot 2023-04-27 at 12 37 40 PM" src="https://user-images.githubusercontent.com/98115742/235005697-961c4e17-c834-4f8d-a4fb-1bdc42e77c9c.png">
