### ISSUE TITLE
survey

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#7]
Which course: 1 Getting Started What type of content: survey URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2018/courseware/066b0480b13046e396208ef51d5c790b/7f15846e372741c483ee67f37d93f346/?child=first Description: When you choose an answer  all the list shifts on the left.  other comments:  your name: Kitkatniss screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel: To do : ELla Ask for more  not able to reproduce the bug

**Comment by EllaHa** [comment]
Not able to reproduce this bug

**Comment by Kitkatniss** [comment]
I've sent you a mp3 of this on Slack.

**Comment by EllaHa** [comment]
This must be a problem of the iframe. I am looking into it but not sure to be able to solve it.

**Comment by EllaHa** [comment]
@mgoudz  any clue? I am sending to you the mp4 on slack since I can't upload it here.

**Comment by Kitkatniss** [comment]
=#198

**Comment by mgoudz** [comment]
I see the issue - the next and back buttons are not visible until you scroll (inner scroll) down. I have changed the layout to be more compact so hopefully those buttons appear. The Qualtrics theme (survey platform) needs to be updated by the company to customize the next/back buttons so they stand out from the edX platform buttons. I have requested that conversion, but it may take a few days.
