### ISSUE TITLE
completion of exercices

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#70]
Which course: 3 Modular Programming and Memory Management What type of content: completion of exercices URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/course/#block-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018+type@chapter+block@9afb1233a3d74a62acc1625236e57a96 Description:  working with function activity  : I did both exercices  they are 100%  But the list of tasks isn't updated (no green sign) other comments:  your name: Kitkatniss screenshot: firefox_2018_09_21_18-34-24.png Codecast timing:  Tasgrader code submitted:  Operating system: Windows 10 which web browser? Firefox Quantum 61.0.2(64 bits) Status actuel:

**Comment by EllaHa** [comment]
![image](https://user-images.githubusercontent.com/19490273/46406164-ec213600-c70a-11e8-85ab-d36cc544db32.png)

**Comment by EllaHa** [comment]
@chrissmiller any clue why this?

**Comment by EllaHa** [comment]
I think this was related to previous problems with lti links. Isn't it? We might be able to close this now.

**Comment by Kitkatniss** [comment]
I asked other testers, it seemed to be usual on edx

Close this
