### ISSUE TITLE
Typo (course 6)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#701]
In the provided commands following the [video about mv command,](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.06+1T2020/courseware/953455675ecb40e491f6645e3711295f/0f6bc45e0328471ba775d27853a83b82/4?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.06%2B1T2020%2Btype%40discussion%2Bblock%4077b4b5e2b6c24fcf91eeb945d5043735) there is a "RENANMING" in some comment.

**Comment by AadhyaKocha** [comment]
The typo was in my HTML description of a command. Corrected now :)
