### ISSUE TITLE
Some weird issue with a Codecast lecture page

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#704]
[see this thread](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/a02d963c6a195d731b771d8a5803a2c0858af518/threads/60bb5575e136290480b29c05)

**Comment by EllaHa** [comment]
Thanks for reporting this issue Isabelle, we are working on it.

**Comment by EllaHa** [comment]
Fixed
