### ISSUE TITLE
Iframe problem with WebLinux - iframe too big for my screen

### ISSUE THREAD

**Issue by EllaHa** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#709]
weblinux is bigger than the edX design
 
the weblinux window is cute and I can't it entirely
![image](https://user-images.githubusercontent.com/19490273/122806218-5bc81c80-d2ca-11eb-9987-641755b27608.png)

**Comment by AadhyaKocha** [comment]
Change width to 103% and height to 650px and make a note to push for full screen view

**Comment by AadhyaKocha** [comment]
Changed in Mooc 6 and 7
