### ISSUE TITLE
Incorrect Code but Taskgrader Marks as Correct

### ISSUE THREAD

**Issue by marchill23** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#711]
I recently discovered a post on the forum where a student submitted an incorrect solution to the activity: [Unit 2.2: Using arrays of integers](https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020+type@sequential+block@7f90c0855f624fbfa70cedcdc1ba212e/block-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020+type@vertical+block@a2218f3b531d4f84ad3ab91d0e4294b9). this is the code they used:

#include <stdio.h>
int main(){
           printf("43");
            return 0;
}

**Comment by AadhyaKocha** [comment]
Added another test
