### ISSUE TITLE
reply to this student

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#712]
Hi Mike,
Learner patrick642@yahoo.com emailed support claiming there were glitches/incorrect grading that caused them to not receive a certificate. They said:
"But it is quite clear there are MULTIPLE errors in the grading system in EACH section of this course THAT WERE NEVER CORRECTED!!!! As such, we receive incorrect grading. For example, an alternative for SUPER USER is ROOT USER yet is was marked as incorrect, because we added 'USER' to the answer!! --- We have been using ROOT USER in the real world for decades. (I've used it for Firewalls, Routers and in Unix/Linux)."

Would the course team want to whitelist this learner or be willing to reach out to them directly?

**Comment by AadhyaKocha** [comment]
@EllaHa is reaching out to edX to tell them that we are in contact with the learner. I have emailed Patrick and will keep you all posted with what he says.

**Comment by AadhyaKocha** [comment]
No response from him so I think he is alright now.
