### ISSUE TITLE
Irrelevant title for Taskgrader activity (course 2)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#713]
In ["Swap first and last name"](https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020+type@sequential+block@914396655d9144bfaf7bd9710bc7415e/block-v1:Dartmouth_IMTx+DART.IMT.C.02+1T2020+type@vertical+block@90efc59aca614504b8058bb25d2fa393) (shouldn't it be "names" by the way?) activity, we're told that this is about using null terminator.
But null terminator doesn't appear in solution, as we just need to read two strings and to print them in reversed order.

**Comment by AadhyaKocha** [comment]
Changed both names to "Swap first and last names" to remove confusion.
