### ISSUE TITLE
video welcome video course 4 - incorrect subtitles and transcripts

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#715]
In [welcome section of course 4](https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2020+type@sequential+block@bed2976f59604bc1ae11e7aff468021d/block-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2020+type@vertical+block@fa2895f2f3474dc6a25c736b1438e9e2), subtitles and transcripts are the ones of last video of previous course.

**Comment by AadhyaKocha** [comment]
Works perfectly now. Thanks @mgoudz!
