### ISSUE TITLE
EDX MOOC 3.1. - Activity : Program a smart unit converter - Worked in the codecast sandbox but error in "Solve box". Please help.

### ISSUE THREAD

**Issue by Narka0** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#719]
#include <stdio.h>
int main (void)
{
    int nbConversions;
    int i;
    double conversiontobemade;
    double conversion;
    char unit='\0';
    scanf("%d\n", &nbConversions);
    for (i=0; i<nbConversions; i++)
    {
        scanf("%lf %s\n", &conversiontobemade, &unit);
        if (unit=='m')
        {
            conversion=3.2808*conversiontobemade;
            printf("%lf ft\n", conversion);
        }
        if (unit=='g')
        {
            conversion=0.002205*conversiontobemade;
            printf("%lf lbs\n", conversion);
        }
        if (unit=='c')
        {
            conversion=32+1.8*conversiontobemade;
            printf("%lf f\n", conversion);
        }
    }
    return(0);
}

**Comment by deladan** [comment]
Hello @Narka0 ,
Issue lies with the fact you've used %s format specifier to read the unit, while your unit variable is of type char, and not an array of char.  
Which format specifier should you use instead?   

But I don't think you should ask for help about your programs here.
This is dedicated for reporting issue with the grader, or possible improvement.

**Comment by AadhyaKocha** [comment]
Hello @Narka0, 
Please ensure you ask questions on the forum as going forwards we will not be able to answer questions here. We would really appreciate that. We use this Github repository for internal use only.

You need to add a multiplication sign in:
`conversion=3.2808conversiontobemade;`

This will allow the code to run and be tested by our grader. The codecast works differently and does not have as extensive testing for your purposes so I would focus on reading carefully what the solver error mentions when you run it.
