### ISSUE TITLE
Not enough test (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#720]
For [activity about dividing decimal](https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@sequential+block@4c4f062124eb47f99ab23cf7228a1109/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@vertical+block@47f831540e1a48acbee34a352ec3fa6e), Taskgrader accepts following code, even if it doesn't give expected results, for instance for 6.6 and 3.3 in input:  
```
#include <stdio.h>
int main(void){
   double books;
   double cash;
   int bkspurch;
   scanf("%lf" ,&books);
   scanf("%lf" ,&cash);
   bkspurch = (int)books/cash;
   printf("%d" ,bkspurch);
   return 0;
    
}
```
Shouldn't some test be added to make sure only correct programs are accepted?

**Comment by AadhyaKocha** [comment]
Test case added:
Input
6.6
1.3

Output
5
