### ISSUE TITLE
Inconsistency between problem statement and provided solution (course 7)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#721]
In [activity about using the math library](https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020+type@sequential+block@20c36bf48d224858a37200c5de92cf3f/block-v1:Dartmouth_IMTx+DART.IMT.C.07+1T2020+type@vertical+block@773e7666937f452d820aab6dd21d90ee), our program is expected to read an integer number from input in order to print its square root.  
However, solution uses a variable of type double.

**Comment by AadhyaKocha** [comment]
@deladan The code still works for integer and double inputs and should not affect if students use integer type. Is there a specific error case we are trying to fix by changing the solution?

**Comment by deladan** [comment]
Hello @AadhyaKocha ,
There is no error and no issue with the grader, but I think solution doesn't exactly match problem statement.
Is it such a great deal to change it?

**Comment by AadhyaKocha** [comment]
Nope it is an easy fix- just wondering if there is a specific thing to address. Thank you!

**Comment by AadhyaKocha** [comment]
Fixed!
