### ISSUE TITLE
Suggestion of clarification on Name your variables Lecture (course 1)

### ISSUE THREAD

**Issue by marchill23** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#723]
Some students have [posted on the forum](https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/discussion/forum/517e9b8f3b9731adf777bfbf13276713572ea886/threads/61a1788df309f70477b1feb2) about possibly clarifying that variable names can start with underscores. A simple text could be added to summarize the do's and don'ts and include it there rather than creating a new video.

**Comment by deladan** [comment]
See issue #683

**Comment by AadhyaKocha** [comment]
Added comment under lecture video
