### ISSUE TITLE
Not enough tests ? (course 1)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#724]
On activity about dividing decimals, following code has been accepted by the grader though it doesn't give expected results when I test it with the first example data on my system:  

```
#include <stdio.h>
int main(void) {
        double dOne,dTwo;
        int iOne,iTwo;
        //printf("The amount of money is having for purcashe a book: \n");
        scanf("%lf",&dOne);
        //printf("The price per book is: \n");
        scanf("%lf",&dTwo);
        //printf("The number of books can be purcase by the given amount: \n");
        //iOne = (double) dOne;
        //iTwo = (double) dTwo;
        printf("%.lf",dOne/dTwo);

        return 0;
}
```

**Comment by AadhyaKocha** [comment]
@deladan Can you please send a link for this activity? I was unable to find it

**Comment by deladan** [comment]
My bad.  
[There it is](https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@sequential+block@4c4f062124eb47f99ab23cf7228a1109/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@vertical+block@47f831540e1a48acbee34a352ec3fa6e).

**Comment by AadhyaKocha** [comment]
Issue was that there was no test case of the value of output above 0.5 rounding. Added test case: 
Input
48.0
3.50
Output
13
