### ISSUE TITLE
Correct option marked incorrect by grader

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#732]
In this [quiz](https://telecom-paris.france-ioi.org/en/#/activities/by-id/1272350288227256715;path=4702,458602124916982205,4769434107088212490,8123435593727593341,933119068612598309;parentAttempId=0/details), I did q3 twice both times marking option A as correct.
The first time, it marked A as incorrect so i repeated and tried every option and every option was marked wrong.
![screencapture-telecom-paris-france-ioi-org-en-2022-02-21-22_21_14](https://user-images.githubusercontent.com/51734801/155058169-353b49d7-0519-49d6-bfd1-cd4106a7183c.png)
I then marked A and submitted and it accepted it weirdly despite marking it incorrect the first time:
![screencapture-telecom-paris-france-ioi-org-en-2022-02-21-22_26_23](https://user-images.githubusercontent.com/51734801/155058204-d6495de5-be8e-4a0e-afef-331c198a948b.png). 
I could not replicate this error in the same quiz, but did this happen to anyone else?

**Comment by catherinechoww** [comment]
Unable to reproduce error and have not seen any learners encounter it either - bug must be resolved.
