### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#733]
All the quizzes have a slight horizontal scroll:
<img width="1440" alt="Screenshot 2022-02-21 at 10 43 02 PM" src="https://user-images.githubusercontent.com/51734801/155059242-266aea12-6c3a-44d5-a1ae-678138177818.png">.
Not enough to disrupt learning but just a little annoying to fidget with.

**Comment by catherinechoww** [comment]
<img width="1006" alt="Screen Shot 2023-05-08 at 3 50 37 PM" src="https://user-images.githubusercontent.com/98115742/236973964-bcaeadcb-cc18-440f-bcdb-5a8a3a283018.png">
As seen in attached screenshot of the same quiz that was used in an example earlier, horizontal scroll is gone from quizzes.
