### ISSUE TITLE
Show chronology to learners

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#734]
When there are multiple Codecasts for the student to see before reaching the quiz, it is confusing to know which one they are on since they all say "0" on top because the default assigns a grade of 0% to codecasts.
![Screenshot 2022-02-22 at 9 03 51 AM](https://user-images.githubusercontent.com/51734801/155165396-0af84dc1-fbf2-489a-9cce-60bb323b122e.png)
Is it possible to show students their progress through the module? Or remove that 0 from the top?

**Comment by catherinechoww** [comment]
Need to create a new account to test this - Because I have completed all of the assignments, I have a check mark in that spot. Perhaps Josh or Maccullum haven't completed Coursera?

**Comment by catherinechoww** [comment]
No tracks the progress as you watch the codecase. For example, when I'm halfway through the codecast video, half of the circle is "filled" and there is a number "50" in the center instead of "0".
