### ISSUE TITLE
LTI loading error

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#735]
When I clicked on this [quiz](https://www.coursera.org/learn/c-programming-getting-started/gradedLti/R7K25/use-variables-in-loops) the first time I got the screen attached below. On clicking a second time things were back to normal but wanted to make a note of this error.
<img width="1440" alt="Screenshot 2022-02-24 at 11 00 39 AM" src="https://user-images.githubusercontent.com/51734801/155560830-3913fbcc-6c02-4997-9c9f-3042b32b0b4c.png">

**Comment by EllaHa** [comment]
Thanks Aadhya for this report. This error appears the first time a LTI is open by someone. So no worries, this error will not be reproduced by anyone.
