### ISSUE TITLE
Wrong codecast video (coursera)

### ISSUE THREAD

**Issue by catherinechoww** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#737]
[https://www.coursera.org/learn/c-programming-getting-started/gradedLti/Iwt1i/find-the-remainder-in-integer-division](url)

The video for "Finding the Remainder" is not there, and instead the video for "Converting Integers to Decimals" is in that section

- also, sorry I can't figure out how to attach the coursera label to this issue

**Comment by EllaHa** [comment]
Good catch! It has been modified. @catherinechoww if you could look at it on your browser, it would be great!

**Comment by catherinechoww** [comment]
Hi Ella, just checked and it now has the right video! Thanks!
