### ISSUE TITLE
pre course survey change wording

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#739]
In this [survey](https://www.coursera.org/learn/c-programming-language-foundations/supplement/2lzSZ/pre-course-survey), i don't see the component to even open in this window. Can we change the wording to just say "click this link to finish survey"?
<img width="983" alt="Screenshot 2022-03-10 at 9 37 59 AM" src="https://user-images.githubusercontent.com/51734801/157684925-73a1f493-667e-4349-a7ef-16ce098571d7.png">

**Comment by catherinechoww** [comment]
<img width="777" alt="Screen Shot 2023-03-17 at 9 36 34 AM" src="https://user-images.githubusercontent.com/98115742/226005038-c1b3081e-1f6d-4757-9e09-f7fe55c3c282.png">
Updated wording here.
