### ISSUE TITLE
Introduce yourself bug

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#740]
On this [page](https://www.coursera.org/learn/c-programming-language-foundations/discussionPrompt/Nb3UZ/introduce-yourself) I introduced myself. Then deleted the post because I wanted to say more. But I do not have the option to re-introduce myself or see my previous post despite having an option that says view my response:
<img width="902" alt="Screenshot 2022-03-10 at 9 43 41 AM" src="https://user-images.githubusercontent.com/51734801/157686559-e4ee197f-9130-4fdf-8233-0227af09c0ea.png">.

Definitely an edge case but if we want to fix it.

**Comment by catherinechoww** [comment]
Seems like a bug we are unable to fix directly - instead, we added a note to this page encouraging users to visit the actual discussion forum page where they can also view all posts from other users, interact with other users, post more, etc.
