### ISSUE TITLE
Auto update progress

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#742]
Once a learner crosses out of the Algorea platform, they cannot immediately see whether they have made progress as the little check icon does not become a tick automatically unless the page is reloaded. This could take some getting used to for the learner but if there is an easy way to fix this, I recommend we do. Here is a video explaining what I mean:

https://user-images.githubusercontent.com/51734801/157688880-87faf765-3219-498a-9ad9-ee7b1da4730c.mov

**Comment by EllaHa** [comment]
Good catch. We should open an issue at the Coursera partner support.
