### ISSUE TITLE
Completion message not shown

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#744]
On completing the quiz, I get an email for completion and the messages tab looks like I have a new message. But on clicking it there is no new message. Should there be one and it just isn't showing? Cannot show a picture since it shows as seen now.

**Comment by AadhyaKocha** [comment]
https://user-images.githubusercontent.com/51734801/162103317-aa2314b7-e2c7-4580-a5e6-a19f99ce7501.mov

**Comment by EllaHa** [comment]
strange, this is a Coursera Bug. Let's see what happens after launch.

**Comment by catherinechoww** [comment]
Unable to reproduce error on my or Maccullum's courses. Issue seems to be resolved post-launch.
