### ISSUE TITLE
Deadline passed message

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#746]
MOOC 3 shows that the deadline for finishing quizzes has passed. This used to happen on edX too and just wasn't nice. Can we delete this message?
<img width="1434" alt="Screenshot 2022-03-17 at 10 56 14 AM" src="https://user-images.githubusercontent.com/51734801/158831693-c0ae949d-b497-4934-a665-f9862770b717.png">

**Comment by AadhyaKocha** [comment]
Here too:
<img width="1250" alt="Screenshot 2022-03-17 at 11 06 05 AM" src="https://user-images.githubusercontent.com/51734801/158832856-5e994ea4-fefe-4bf4-b194-87796e1eece8.png">

**Comment by EllaHa** [comment]
I think this is because the course hasn't launched yet.

**Comment by catherinechoww** [comment]
I still have the overdue message post-launch of courses. Is this something we want to mention to Coursera support team?

**Comment by catherinechoww** [comment]
Used additional account to test this - found that there's a button that allows you to "Reset Deadlines" when you don't finish the course within the original schedule.
