### ISSUE TITLE
Add to FAQ

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#747]
Codecast loading can take time and might need reloading the page. If performance cannot be improved maybe add this note in the FAQs?

**Comment by catherinechoww** [comment]
<img width="856" alt="Screen Shot 2023-03-30 at 9 41 58 AM" src="https://user-images.githubusercontent.com/98115742/228907441-d4a49cdd-5bdb-46f4-815d-0a9e62830a7a.png">
No general FAQ page on coursera - added a note to this page of every course: [https://www.coursera.org/learn/c-programming-getting-started/supplement/zknT8/learn-how-to-use-codecast-and-taskgrader](url)
