### ISSUE TITLE
Completed courses message

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#749]
Under the completed courses tab, I see MOOC 1, 2, 3 correctly but only MOOC 3's message shows as complete saying "Great work!" Can this message be added to MOOC 1 and 2 as well? 
<img width="1288" alt="Screenshot 2022-04-05 at 9 39 16 AM" src="https://user-images.githubusercontent.com/51734801/161767117-b93620b9-370a-4bca-9453-982e0ad95927.png">

**Comment by catherinechoww** [comment]
Also, I don't get the "Great Work!" message at all - what makes it show up for some users and not others?

**Comment by EllaHa** [comment]
Let's see what happens when the courses launch!

**Comment by catherinechoww** [comment]
All of complete courses now have the message: "Great work! You have passed all requirements and can view your course certificate now." Must be something was fixed when the course was launched.
