### ISSUE TITLE
Multiple choice problem aesthetic (Coursera 4)

### ISSUE THREAD

**Issue by catherinechoww** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#750]
Topic: Use pointers with functions
Activity: pointers and functions

Very minor issue - one of the four answer choices of problem 2 has a larger shaded box than the other three choices, and it just so happens that it's the right answer. (see attached picture) It kind of draws users' eyes to that & might make people unsure of the correct answer choose it and get it correct by chance. Is there a way to make all the answer choices look the same?

<img width="638" alt="Screen Shot 2022-04-05 at 7 23 50 PM" src="https://user-images.githubusercontent.com/98115742/161866999-d7772643-3f5d-4a47-baa6-947eb8af84bc.png">

[https://www.coursera.org/learn/c-programming-pointers-and-memory-management/gradedLti/vHVSN/use-pointers-with-functions](url)

**Comment by AadhyaKocha** [comment]
Similar thing happens here but this is not the right choice.
<img width="1234" alt="Screenshot 2022-04-06 at 9 31 52 PM" src="https://user-images.githubusercontent.com/51734801/162102382-5a634000-4703-4eff-baca-0969b5894527.png">
