### ISSUE TITLE
Coursera Course Menu (Coursera)

### ISSUE THREAD

**Issue by catherinechoww** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#751]
On main dashboard of all courses I'm enrolled in:

- Course 3 shows up under "Home" AND "Completed" despite being a completed course.
- Course 1, 2, and 4 show up in the correct place.
<img width="1115" alt="Screen Shot 2022-04-05 at 8 35 19 PM" src="https://user-images.githubusercontent.com/98115742/161872864-9f6decc7-135e-4904-917b-17715aeb7f01.png">
<img width="1140" alt="Screen Shot 2022-04-05 at 8 35 26 PM" src="https://user-images.githubusercontent.com/98115742/161872875-e2dd4cec-52b5-48b0-aaa6-7043d756febe.png">

**Comment by AadhyaKocha** [comment]
Also a discrepancy in mine where only MOOC 3 shows up in Home despite being in Completed but not MOOC 1 or 2.

**Comment by EllaHa** [comment]
Interesting. I suggest to wait until the course have officially launched to report this issue to Coursera.

**Comment by catherinechoww** [comment]
Doesn't seem to be the issue anymore - issue closed!
