### ISSUE TITLE
Answer options visual

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#755]
Small change: the option A button is smaller than B and C:
<img width="1285" alt="Screenshot 2022-04-07 at 8 53 03 AM" src="https://user-images.githubusercontent.com/51734801/162203312-61eeca1d-e039-486b-a9a8-fe33f335493b.png">

in this [quiz](https://www.coursera.org/learn/c-programming-advanced-data-types/gradedLti/NTVWj/get-to-know-the-concept-of-a-linked-list).

**Comment by EllaHa** [comment]
I think this is because of the size of the solution. Thanks for this feedback for continues improvements.

**Comment by EllaHa** [comment]
Catherine, I suggest to ask Michel for documentation on the taskgrader repo https://github.com/France-ioi/taskgrader

**Comment by catherinechoww** [comment]
Michel has helped us fix this.
