### ISSUE TITLE
Possible confusion with unit in some Taskgrader activity (course 3)

### ISSUE THREAD

**Issue by deladan** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#756]
In the [activity about memory usage displayed](https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2020+type@sequential+block@91f8edcd857f410b82baa1860866f4ae/block-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2020+type@vertical+block@e2bccbddfb4a43058c89c9a810bfd69f), program expects us to display memory using KB unit.
Which is confusing, as 1000 prefix should be k (lowercase).
One might think that K means 1024 as it was the initial meaning of this prefix (now set to Ki).

**Comment by AadhyaKocha** [comment]
https://en.wikipedia.org/wiki/Kilobyte create a quick "please note:"... on the task statement in task editor

**Comment by deladan** [comment]
Hello @AadhyaKocha ,
Adding a note seems a good idea.
But isn't it also possible to rectify Taskgrader so one is expected to display "kB" instead of "KB" which is incorrect?

**Comment by catherinechoww** [comment]
Hi @deladan,

After discussing, we decided that it would be too tedious to change the entirety of the problem to fix the kB/KB dilemma, and that it would be best to just add the note. Thanks for catching this issue!

**Comment by deladan** [comment]
Hello @catherinechoww ,
I understand, but I think it's a pity that problem statement is erroneous, as the correct writing of 1000B should be kB.
Particularly when you want to open a new course (on coursera, if I refer to the label of some issues here). It would be nice if everything were correct.
On the same idea, isn't it possible to remove the "suspicious" coding warnings from Taskgrader?
They seldomly make sense for the learners.
