### ISSUE TITLE
error trying to get correct answer (coursera 6)

### ISSUE THREAD

**Issue by catherinechoww** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#758]
Getting quiz 100% correct (it even says so on the page), but getting error message every time I submit. Grade not showing up on grade page.
<img width="353" alt="Screen Shot 2022-04-13 at 12 38 50 PM" src="https://user-images.githubusercontent.com/98115742/163229309-83724544-b2d0-4c36-afb8-998dcb9ebfb6.png">
<img width="118" alt="Screen Shot 2022-04-13 at 3 27 25 PM" src="https://user-images.githubusercontent.com/98115742/163255509-dce08949-5835-425f-bcac-4a67d3a5b357.png">
<img width="921" alt="Screen Shot 2022-04-13 at 12 40 06 PM" src="https://user-images.githubusercontent.com/98115742/163229321-c7aa0ac8-6e63-4f07-b18f-c3aed089b218.png">

[https://www.coursera.org/learn/linux-basics-the-command-line-interface/gradedLti/K6dTg/activity-os-unix-history-and-genesis](url)

**Comment by EllaHa** [comment]
![image](https://user-images.githubusercontent.com/19490273/163397942-1bec6407-ed63-46a6-bf62-3d6f7dc57d7b.png)

**Comment by remisharrock** [comment]
for me same error and in the console I have 
`Loading failed for the <script> with source “https://static-items.algorea.org/files/checkouts/255595fbf0222e1a7d6aa9224535a3d4/06%20Linux%20Basics%20The%20Command%20Line%20Interface/Unit%206.1%20History%20of%20Linux%20and%20the%20command%20line/01%20Discovering%20operating%20systems/01_OsUnixHistoryAndGenesis/grader_data.js”. [index.html:17:1](https://static-items.algorea.org/files/checkouts/255595fbf0222e1a7d6aa9224535a3d4/06%20Linux%20Basics%20The%20Command%20Line%20Interface/Unit%206.1%20History%20of%20Linux%20and%20the%20command%20line/01%20Discovering%20operating%20systems/01_OsUnixHistoryAndGenesis/index.html?taskID=quiz-255595fbf0222e1a7d6aa9224535a3d4&theme=coursera&sToken=eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCJ9.eyJiQWNjZXNzU29sdXRpb25zIjpmYWxzZSwiYkhpbnRzQWxsb3dlZCI6ZmFsc2UsImJJc0FkbWluIjpmYWxzZSwiYlJlYWRBbnN3ZXJzIjp0cnVlLCJiU3VibWlzc2lvblBvc3NpYmxlIjp0cnVlLCJkYXRlIjoiMTQtMDQtMjAyMiIsImlkQXR0ZW1wdCI6IjYzOTQ0MDIwMzE4NDA4MzMzMzgvMCIsImlkSXRlbUxvY2FsIjoiMzc3NDcyMzMzOTcwNTUwOTQ4OSIsImlkVXNlciI6IjYzOTQ0MDIwMzE4NDA4MzMzMzgiLCJpdGVtVXJsIjoiaHR0cHM6Ly9zdGF0aWMtaXRlbXMuYWxnb3JlYS5vcmcvZmlsZXMvY2hlY2tvdXRzLzI1NTU5NWZiZjAyMjJlMWE3ZDZhYTkyMjQ1MzVhM2Q0LzA2IExpbnV4IEJhc2ljcyBUaGUgQ29tbWFuZCBMaW5lIEludGVyZmFjZS9Vbml0IDYuMSBIaXN0b3J5IG9mIExpbnV4IGFuZCB0aGUgY29tbWFuZCBsaW5lLzAxIERpc2NvdmVyaW5nIG9wZXJhdGluZyBzeXN0ZW1zLzAxX09zVW5peEhpc3RvcnlBbmRHZW5lc2lzL2luZGV4Lmh0bWw_dGFza0lEPXF1aXotMjU1NTk1ZmJmMDIyMmUxYTdkNmFhOTIyNDUzNWEzZDRcdTAwMjZ0aGVtZT1jb3Vyc2VyYSIsIm5iSGludHNHaXZlbiI6IjAiLCJwbGF0Zm9ybU5hbWUiOiJhbGdvcmVhX2JhY2tlbmQiLCJyYW5kb21TZWVkIjoiODY2OTQ0OTg4MTQ4MjI0MzE0MSJ9.KbZaNQnMh7JNgeNCOy3-soxfW7mA9Zb7SiTg0nh8zLi4XyKt8wfLOXdy8uJVDhY12WtLJHwvx1M6fSmt3Y572_cq-hXICRlSuTrBwi2Kzs5zx0jEFdayIjcleKA4EtcAep1wSOB8vF9f6jDR0jdNx7XkNaZmE-DT8jwU36286kwbzVe--xzvmNFnxjT-WOS4UTYPk_YeZV1IT_ajNrhFjr_k7L-UwMdgBSN7GwyPwnIGwgv9XuJ6fpbvq3j6yFPshUgmiSTcQ2aR06CSDI9oCa9fy72SDS3D9ZlabFnUKt8TV6DJ0t_XGpF4nf7LfFad-Wuw7Tjje96sbq6ewYtKLg&sPlatform=algorea_backend&channelId=task-1385629011132011515&sLocale=en)`
