### ISSUE TITLE
add video (coursera 6)

### ISSUE THREAD

**Issue by catherinechoww** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#759]
Did we want to put the video here? I notice the edX version has the message and the video.

<img width="893" alt="Screen Shot 2022-04-13 at 3 24 15 PM" src="https://user-images.githubusercontent.com/98115742/163254995-dbcaf3f8-1453-47cd-b08b-b89eef3ffa46.png">

[https://www.coursera.org/learn/linux-basics-the-command-line-interface/supplement/fdEf3/memory-representation-ram-cells-word-byte-bit-memory-address](url)

**Comment by EllaHa** [comment]
you are right. this is solved.
