### ISSUE TITLE
Task Grader message

### ISSUE THREAD

**Issue by AadhyaKocha** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#761]
Very minor but when tests pass, the success message "congratulations" is only on the first test and not the second (on both Coursera and edX). 
<img width="880" alt="Screenshot 2022-04-14 at 8 38 00 AM" src="https://user-images.githubusercontent.com/51734801/163392316-f3dcd199-3494-44c3-aeb9-6d58a3165c79.png">

**Comment by remisharrock** [comment]
this is indeed correct you have to click the grey bar , I explain this in the taskgrader tutorial (new one that I did last weekà
