### ISSUE TITLE
Code formatting has been changed on updated forum

### ISSUE THREAD

**Issue by joshMeise** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#772]
The edX forum has been updated, so using command + k no longer works to format code. The FAQ and pinned posts will need to be updated. Here is a link that shows how it can now be formatted: [https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/course_components/create_html_component.html](url)

**Comment by catherinechoww** [comment]
Draft of tutorial:

[https://docs.google.com/document/d/1luZr7_uwIQXnd2-Gio1EZqLRYo8p9oUVW-e9zeOZAkY/edit?usp=sharing](url)
