### ISSUE TITLE
Issue with solution evaluation on edX

### ISSUE THREAD

**Issue by joshMeise** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#773]
[https://learning.edx.org/course/course-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@sequential+block@486dacf4bd094519afe1c91af2e17fee/block-v1:Dartmouth_IMTx+DART.IMT.C.01+1T2020+type@vertical+block@d596c6b0555d4fe8b3c0d6b0912b8a00](url). This MOOC has been evaluating the correct answer on problem 3 to be incorrect.

**Comment by EllaHa** [comment]
Hi Josh, thanks for letting us know. 

@catherinechoww can you try to test it and see if you can reproduce this error. 
@joshMeise do have any screenshots of the error? 
Thanks, 

Best,

**Comment by joshMeise** [comment]
Dear Ella,

I unfortunately deleted the screenshot from the forum since it contained the solution, but I had shown @catherinechoww  before doing so. I am trying to produce the same error with both my main account and an alternative account, but it is evaluating the answer as correct now.

Best,
Josh

**Comment by remisharrock** [comment]
I do have a score of 100 with these answers. Seems ok right ?
![image](https://user-images.githubusercontent.com/8048877/198910239-abc3200f-62c8-4c9d-9d73-68e19403de55.png)

**Comment by catherinechoww** [comment]
Seeing that we are unable to reproduce this error, it does not seem to be an issue anymore. Users must just remember that number 1 is a trick question - just because we recommend against using an underscore at the start of a variable name does not mean the program does not accept it.
