### ISSUE TITLE
User "Rameses"

### ISSUE THREAD

**Issue by EllaHa** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#776]
a STAR discussion forum participant. I believe he started off as one of the beta testers but I found that he's answering a lot of discussion post questions. See an example below.
https://www.coursera.org/learn/c-programming-getting-started/discussions/forums/6_MuQZmsEeywKQ5FRIY4Ew/threads/4zx6v1BfEe2vVg6vl34jZQ
He answers right away, and he provides really good insight.
But is he providing too much information? Almost to the point that he's giving away answers? See another example of his posts:
https://www.coursera.org/learn/c-programming-getting-started/discussions/forums/GJ9x-0baEeyjMxIGDBazAw/threads/w4jCBkjqEe2GWw5xCmtijQ
Either way, should we reach out to him to thank him or make him a community TA? And if he IS providing too much of an answer, should we address that?

**Comment by EllaHa** [comment]
Ella sends a demand to partner Coursera to grant him access

**Comment by EllaHa** [comment]
Email sent on December 1srt

**Comment by catherinechoww** [comment]
Coursera has made him a "mentor" on the forum.
