### ISSUE TITLE
Discussion Post Bug:

### ISSUE THREAD

**Issue by EllaHa** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#777]
Unable to edit or delete people's discussion posts - I keep on getting an error.
For example, I want to delete code from the following post because it contains very close to the final answer:
https://www.coursera.org/learn/c-programming-getting-started/discussions/forums/7MFmFaCDEeyZlw6FWWoo7w/threads/YO0oSVoDEe2VNw5236r8hQ
Is this something we need to tell Coursera about?

**Comment by catherinechoww** [comment]
See an example here: <img width="698" alt="Screen Shot 2022-12-01 at 8 08 29 AM" src="https://user-images.githubusercontent.com/98115742/205102378-bd8920e7-28ba-4046-a3e5-c440fc28f96e.png">

**Comment by EllaHa** [comment]
Email send to Coursera support on December 1srt

**Comment by catherinechoww** [comment]
Changing all TA roles to "Teaching Staff" enabled the editting and deletion of discussion forum posts.
