### ISSUE TITLE
Week 2 forum thread:

### ISSUE THREAD

**Issue by EllaHa** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#778]
There doesn't seem to be a thread for Week 2 forum posts. I noticed some people posting week 2 questions under week 1.

![image](https://user-images.githubusercontent.com/19490273/202498314-c2fec87a-7962-4776-a6df-3ba73cd49dbb.png)

**Comment by catherinechoww** [comment]
I think we need to rename the Week 1 discussion thread to "Week 2" and the Welcome discussion thread to "Week 1".

**Comment by catherinechoww** [comment]
Emailed Coursera support on 12/8/2022

**Comment by catherinechoww** [comment]
Received assistance from Coursera support - They said that we should be able to move discussion threads from one week to another. Catherine will work with Mike to do so.

**Comment by catherinechoww** [comment]
Unless I am misunderstanding the Coursera support team - I'm actually unable to do so. See video example of what I am trying to do.

https://user-images.githubusercontent.com/98115742/209384278-97da49f4-d798-43d6-857b-ba45635c75bb.mov

**Comment by catherinechoww** [comment]
Made new threads in the correct weeks, manually moved one discussion from its old, incorrect thread to its new, correct thread. Complete!
