### ISSUE TITLE
MOOC 5, User "Rey Manuel"

### ISSUE THREAD

**Issue by EllaHa** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#779]
Happy to see that Rey Manuel is correctly working through the course, but he posts the answer on the forum when he solves it. See example below.
https://www.coursera.org/learn/c-programming-advanced-data-types/discussions/forums/aflWnLMmEeyqSwqj3k2Djw/threads/zNR9nUSfEe2U7RLtxyc8mQ
This was all happening around a month ago. He's stopped doing it but I still want to delete his posts ... but can't do that because of the bug discussed earlier.

**Comment by catherinechoww** [comment]
Can be deleted now that TA's have the ability to delete discussion posts.
