### ISSUE TITLE
new tool

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#78]
Which course: 4 Pointers and Memory Management What type of content: new tool URL: https://cdecl.org/ Description: This is just a suggestion to check this app that I think is a great idea... Any possibility to incorporate it in the mix?  ) other comments:  your name: Godefroy screenshot:  Codecast timing:  Tasgrader code submitted:  Operating system:  which web browser?  Status actuel:

**Comment by GodefroyClair** [comment]
Yeah, to follow up, it's one of those tools based on _parser_ that I have seen here and there. I think they have a great potential to learn many things... including C.
Just to give more example, here is a tools of the same "parser" family applied to the learning of natural deduction developed by a friend, Olivier Pons, who is teaching in France:
http://cedric.cnam.fr/~pons/DEDUCTION/deduction1.html (from a friend)
If this inspires you, I would be happy to collaborate on creating exercices based on those ideas...

**Comment by petraBT** [comment]
Thank you, @GodefroyClair for this  suggestion! We will look into this idea once we finish fixing issues amongst the currently existing resources. For now I am closing this issue.
