### ISSUE TITLE
Student unable to access activities on coursera

### ISSUE THREAD

**Issue by Apaquet37** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#796]
I know this has been a problem in the past, and that the issue usually resolves itself, but I have a student who is not able to load the course content. Any suggestions?

<img width="858" alt="Screenshot 2024-07-30 at 11 48 35 PM" src="https://github.com/user-attachments/assets/e44f1a42-9acf-449c-8a66-eabd978f34e7">

**Comment by mathias-hiron** [comment]
This is from last july, were there recent complains about the same issue?
I just tested the task here and it loaded correctly:
https://telecom-paris.france-ioi.org/en/a/1631088781244523248;p=4702,458602124916982205,5545851358845115755,4692018957656127760,5822310968611219975;a=0

**Comment by remisharrock** [comment]
@mathias-hiron maybe it's linked with 
https://github.com/France-ioi/taskgrader/issues/125
 ?

**Comment by Apaquet37** [comment]
I think we're good to go on this specific loading issue! But it does lead into the issue that Remi just linked above.
