### ISSUE TITLE
Learners unable to access solve tab

### ISSUE THREAD

**Issue by Apaquet37** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#800]
This happened before over the summer, but is being reported again by multiple learners. 

[Previous issue](https://github.com/remisharrock/c-programming-with-linux-MOOC-issues-tracker/issues/795#issue-2418755871)

**Comment by Apaquet37** [comment]
Workaround possible by clicking on hints and then the back button in the browser. issue #124 in taskgrader

**Comment by mblockelet** [comment]
Hi @Apaquet37 and everyone,

There was indeed an issue, which is now fixed. Could you confirm with the learners that they don't encounter the issue anymore?

**Comment by Apaquet37** [comment]
@mblockelet yep! Will do.
