### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#83]
Which course: 3 Modular Programming and Memory Management What type of content: Main page URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/course/#block-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018+type@sequential+block@853841a4bcc245efb4e938b953538b28 Description: The green  check  icons are not accurate  some tasks that I have succeeded (all tabs are checked in the Unit page) are not considered as checked on the main page. See screenshots for examples other comments:  your name: Godefroy screenshot: godot clair - Capture d’e?cran 2018-09-21 a? 22.06.34.png godot clair - Capture d’e?cran 2018-09-21 a? 22.03.03.png  Codecast timing:  Tasgrader code submitted:  Operating system: Apple's macOS (formerly OS X) which web browser? Chrome 68.0.3440.106  64bits Status actuel:

**Comment by petraBT** [comment]
@EllaHa @mgoudz Is there anything that can be done about this or is this just the way edX works?

**Comment by mgoudz** [comment]
This is just the way edX works. We could add a topic in FAQ about the green check marks.
