### ISSUE TITLE
quizz

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#87]
Which course: 4 Pointers and Memory Management What type of content: quizz URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.04+1T2018/courseware/27b25e631c254ed09e1f67d84f02a01c/2f01c383f1174864ae2643ecc675db50/?child=first Description: The right answer is not accepted for the last question of the activity  pointers and functions  in my opinion. The answer should be 3 but it is refused.  int numbers[] = {4  -1  8  3  0  -11}   You have furthermore declared a pointer via  int *ptr   and initialized it via  ptr = numbers + 2   and then executed ptr++   What is *ptr ? other comments:  your name: Godefroy screenshot: see  godot Clair - Capture d’e?cran 2018-09-21 a? 23.36.54.png   Codecast timing:  Tasgrader code submitted:  Operating system: Apple's macOS (formerly OS X) which web browser?  Status actuel:

**Comment by petraBT** [comment]
Fixed.
