### ISSUE TITLE
to do list

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#88]
Which course: 3 Modular Programming and Memory Management What type of content: to do list URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/5c40ed165b45423496c1c8c8fdca08d9/91f8edcd857f410b82baa1860866f4ae/2?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.03%2B1T2018%2Btype%40vertical%2Bblock%40774d7e54673b44ef957688dbf77c0fa7 Description: In the top the screen  the to do list is green but I made a bad submission  so :  it should stay red  isn't it ? or orange at least...  If I want to track what I've done and what I still have to do  it would be easier. other comments:  your name: Kitkatniss screenshot: firefox_2018-09-21_23-40-14.png Codecast timing:  Tasgrader code submitted:  Operating system: Windows 10 which web browser? Firefox Status actuel:

**Comment by petraBT** [comment]
I am guessing we can't communicate that level of detail from taskgrader to the edX platform? Or can we?

**Comment by mgoudz** [comment]
Right @petraBT b/c the green check means you visited the page and this Taskgrader is an LTI, we can't control the check mark with Taskgrader input.
