### ISSUE TITLE
Activity: use the dot operator

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#90]
Which course: 5 Advanced Data Types What type of content: Activity: use the dot operator URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.05+2T2018/courseware/58099ea386614233830b63363dc6db01/a667ef845e5e474e974ccea13bf5d03b/1?activate_block_id=block-v1%3ADartmouth_IMTx%2BDART.IMT.C.05%2B2T2018%2Btype%40vertical%2Bblock%403b79179ddf4c4c069c47e637ddc18c78 Description: I can't view different answer choix of the first question of QUIZ. There are only  an incorrect answer   and  the correct answer .  other comments:  your name:  screenshot: Lei TAN - U5.use_the_dot_operator_LEI.JPG Codecast timing:  Tasgrader code submitted:  Operating system: Windows 10 which web browser? Both IE and Chrome Status actuel:

**Comment by petraBT** [comment]
resolved
