### ISSUE TITLE
Codecast  sound of the Codecast

### ISSUE THREAD

**Issue by remisharrock** [remisharrock/c-programming-with-linux-MOOC-issues-tracker#91]
Which course: 3 Modular Programming and Memory Management What type of content: Codecast  sound of the Codecast URL: https://courses.edx.org/courses/course-v1:Dartmouth_IMTx+DART.IMT.C.03+1T2018/courseware/5c40ed165b45423496c1c8c8fdca08d9/f8d1f6fe61704a3194260a8c284a61a3/ Description: after the sentence  So now let's go through this program step by step.   there's a short unexpected sound other comments:  your name: Kitkatniss screenshot:  Codecast timing: 2'38 Tasgrader code submitted:  Operating system: Windows 10 which web browser? Firefox Status actuel:

**Comment by petraBT** [comment]
This is about "Scope and functions in C: scope of variables when using functions" - very short slight sound. Not worth re-recording.
